// fcp_v2_assets/languages.js
// ไฟล์สำหรับเก็บคำแปลทั้งหมด

export const translations = {
    // English
    en: {
        appTitle: "Football Scoreboard Controller - V2.6",
        excel: "Excel",
        matchId: "ID:",
        load: "Load",
        teamA: "Team A",
        teamB: "Team B",
        edit: "Edit",
        editHint: "Edit name or add new line with /",
        ok: "OK",
        label1: "Label 1",
        label2: "Label 2",
        label3: "Label 3",
        swap: "Swap Teams",
        reset: "Reset",
        fullReset: "Full Reset",
        score2Label: "Fouls/Counts",
        hide: "Hide",
        show: "Show",
        score2VisibilityGroup: "Score 2 Visibility Control",
        resetKeybinds: "Reset Keybinds", // NEW
        resetColors: "Clear Team Color Memory", // NEW
        half: "Half",
        injuryTime: "Added Time",
        countdown: "Down",
        countdownHint: "Countdown Timer",
        resetToZeroHint: "Reset timer to 00:00",
        resetToStartHint: "Reset timer to configured start time",
        settings: "Settings",
        copy: "Copy",
        help: "Help",
        donate: "Donate",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "Update Version 2.6",
        detailsTitle: "Settings & Announcement", // Changed title
        detailsDesc: "Customize global settings below.", // Changed description
        tagsTitle: "Available Tags for Announcement", // Changed title
        keybindsTitle: "Custom Keyboard Shortcuts", // NEW
        keybindsList: [ // NEW
            { id: "scoreA_plus", label: "+ Score A (Main)", default: "1" },
            { id: "scoreA_minus", label: "- Score A (Main)", default: "2" },
            { id: "scoreB_plus", label: "+ Score B (Main)", default: "4" },
            { id: "scoreB_minus", label: "- Score B (Main)", default: "5" },
            { id: "score2A_plus", label: "+ Score A (Sub)", default: "7" },
            { id: "score2A_minus", label: "- Score A (Sub)", default: "8" },
            { id: "score2B_plus", label: "+ Score B (Sub)", default: "9" },
            { id: "score2B_minus", label: "- Score B (Sub)", default: "0" },
            { id: "timer_playpause", label: "Play/Pause Timer", default: " " },
            { id: "timer_resetstart", label: "Reset to Start Time", default: "F10" },
            { id: "timer_togglehalf", label: "Toggle Half", default: "F11" },
            { id: "full_reset", label: "Full Reset (All)", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Team A Name' },
            { code: '&lt;TeamB&gt;', desc: '- Team B Name' },
            { code: '&lt;score_team_a&gt;', desc: '- Team A Score' },
            { code: '&lt;score_team_b&gt;', desc: '- Team B Score' },
            { code: '&lt;score2_team_a&gt;', desc: '- Team A Score 2 (Fouls/Counts)' },
            { code: '&lt;score2_team_b&gt;', desc: '- Team B Score 2 (Fouls/Counts)' },
            { code: '&lt;time_counter&gt;', desc: '- Current Time (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Half (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Label 1 Text' },
            { code: '&lt;label2&gt;', desc: '- Label 2 Text' },
            { code: '&lt;label3&gt;', desc: '- Label 3 Text' },
        ],
        save: "Save",
        close: "Close",
        saveAndUpdate: "Save & Update",
        helpTitle: "How to Use",
        helpStep1: "1. Click the <i class='fas fa-folder-open'></i> icon to set your logo folder path. The default is <code>C:/OBSAssets/logos</code>. **You need to click the Edit button inside the popup to change and save the path.**",
        helpStep2: "2. Click <i class='fas fa-file-excel'></i> Excel button to select your data file.",
        helpStep3: "3. Select the desired Match ID and click <i class='fas fa-check'></i> Load.",
        sourcesTitle: "Required OBS Sources",
        sourcesTableHeaders: ["Source Name", "Source Type", "Details"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'Team A (Primary Color)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'Team B (Primary Color)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'Team A (Secondary Color)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'Team B (Secondary Color)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'Team A Logo' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'Team B Logo' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'Team A Name' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'Team B Name' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'Team A Score (Main)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'Team B Score (Main)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'Team A Score 2 (Fouls/Counts)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'Team B Score 2 (Fouls/Counts)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'Label 1 Text' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'Label 2 Text' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'Label 3 Text' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'Half (1st/2nd)' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'Timer' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'Added Time (+1)' },
        ],
        understand: "Got it",
        donateTitle: "Support Us",
        donateThai: "For Thais (for Scoreboard)",
        donateForeign: "For Foreigners (Outside Thailand)",
        timeSettingsTitle: "Set Start Time",
        timeSettingsMinutes: "Minutes",
        timeSettingsSeconds: "Seconds",
        logoPathTitle: "Logo Folder Path",
        logoPathDesc: "The current logo folder path is:",
        logoPathHint: "Set logo folder path",
        changelogTitle: "Update History",
        changelogContent: `
            <ul class="changelog-list">
                <li>
                    <h5>Version 2.6 (Latest)</h5>
                    <ul>
                        <li>**Custom Key Bindings:** Added a settings panel to customize keyboard shortcuts.</li>
                        <li>**Team Color Management:** Added an option to clear saved team colors.</li>
                        <li>**Score 2 Visibility:** Control moved to the main settings for stable hiding/showing.</li>
                        <li>**Announcement:** Loads from <code>fcp_v2_assets/announcement.txt</code>.</li>
                        <li>**Features:** Full Reset, Global Key Listener, Score 2 controls added.</li>
                        <li>**UI:** Improved Help Sources to an easy-to-copy table format.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "Please upload a file first",
        toastMatchNotFound: "Match ID not found:",
        toastLoaded: "Loaded ID:",
        toastSuccess: "Success",
        toastSwapped: "Teams swapped",
        toastNoTextToCopy: "No text to copy",
        toastCopied: "Copied to clipboard",
        toastCopyFailed: "Copy failed",
        toastScoreReset: "Score reset",
        toastScore2Reset: "Score 2 reset",
        toastFullReset: "Scoreboard fully reset",
        toastCopiedSourceName: "Copied source name:",
        toastSaved: "Saved",
        toastKeybindsSaved: "Keybinds saved!", // NEW
        toastColorsCleared: "Team color memory cleared!", // NEW
        toastObsError: "Failed to connect to OBS",
        toastInvalidTime: "Invalid time format. Please check minutes and seconds (0-59).",
        toastTimeSet: "Start time has been set and updated.",
    },
    // ภาษาไทย
    th: {
        appTitle: "โปรแกรมควบคุมสกอร์บอร์ดฟุตบอล - V2.6",
        excel: "Excel",
        matchId: "ID:",
        load: "โหลด",
        teamA: "ทีม A",
        teamB: "ทีม B",
        edit: "แก้ไข",
        editHint: "แก้ไขชื่อ หรือขึ้นบรรทัดใหม่ด้วยการใส่ /",
        ok: "ตกลง",
        label1: "ป้าย 1",
        label2: "ป้าย 2",
        label3: "ป้าย 3",
        swap: "สลับฝั่ง",
        reset: "รีเซ็ต",
        fullReset: "รีเซ็ตทั้งหมด",
        score2Label: "ฟาวล์/แต้ม 2",
        hide: "ซ่อน",
        show: "แสดง",
        score2VisibilityGroup: "ควบคุมการแสดงผลคะแนน 2",
        resetKeybinds: "รีเซ็ตคีย์ลัด", // NEW
        resetColors: "ล้างหน่วยความจำสีทีม", // NEW
        half: "ครึ่ง",
        injuryTime: "ทดเวลา",
        countdown: "นับถอยหลัง",
        countdownHint: "ตัวนับเวลาถอยหลัง",
        resetToZeroHint: "รีเซ็ตเวลาเป็น 00:00",
        resetToStartHint: "รีเซ็ตตามเวลาที่ตั้งค่า",
        settings: "ตั้งค่า",
        copy: "คัดลอก",
        help: "วิธีใช้",
        donate: "สนับสนุน",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "อัปเดตเวอร์ชัน 2.6",
        detailsTitle: "ตั้งค่า & ข้อความประกาศ", // Changed title
        detailsDesc: "ตั้งค่าทั่วไปและข้อความประกาศด้านล่าง", // Changed description
        tagsTitle: "Tags ที่ใช้งานได้สำหรับข้อความประกาศ", // Changed title
        keybindsTitle: "ตั้งค่าคีย์ลัด (Keyboard Shortcuts)", // NEW
        keybindsList: [ // NEW
            { id: "scoreA_plus", label: "+ คะแนน A (หลัก)", default: "1" },
            { id: "scoreA_minus", label: "- คะแนน A (หลัก)", default: "2" },
            { id: "scoreB_plus", label: "+ คะแนน B (หลัก)", default: "4" },
            { id: "scoreB_minus", label: "- คะแนน B (หลัก)", default: "5" },
            { id: "score2A_plus", label: "+ คะแนน A (รอง)", default: "7" },
            { id: "score2A_minus", label: "- คะแนน A (รอง)", default: "8" },
            { id: "score2B_plus", label: "+ คะแนน B (รอง)", default: "9" },
            { id: "score2B_minus", label: "- คะแนน B (รอง)", default: "0" },
            { id: "timer_playpause", label: "เริ่ม/หยุด เวลา", default: " " },
            { id: "timer_resetstart", label: "รีเซ็ตไปเวลาเริ่มต้น", default: "F10" },
            { id: "timer_togglehalf", label: "สลับครึ่งเวลา", default: "F11" },
            { id: "full_reset", label: "รีเซ็ตทั้งหมด", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ชื่อทีม A' },
            { code: '&lt;TeamB&gt;', desc: '- ชื่อทีม B' },
            { code: '&lt;score_team_a&gt;', desc: '- คะแนนทีม A' },
            { code: '&lt;score_team_b&gt;', desc: '- คะแนนทีม B' },
            { code: '&lt;score2_team_a&gt;', desc: '- คะแนน 2 ทีม A (ฟาวล์/แต้ม)' },
            { code: '&lt;score2_team_b&gt;', desc: '- คะแนน 2 ทีม B (ฟาวล์/แต้ม)' },
            { code: '&lt;time_counter&gt;', desc: '- เวลาปัจจุบัน (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ครึ่งเวลา (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ข้อความ Label 1' },
            { code: '&lt;label2&gt;', desc: '- ข้อความ Label 2' },
            { code: '&lt;label3&gt;', desc: '- ข้อความ Label 3' },
        ],
        save: "บันทึก",
        close: "ปิด",
        saveAndUpdate: "บันทึกและอัปเดต",
        helpTitle: "วิธีการใช้งาน",
        helpStep1: "1. กดปุ่ม <i class='fas fa-folder-open'></i> เพื่อตั้งค่าที่อยู่โฟลเดอร์โลโก้ (ค่าเริ่มต้นคือ <code>C:/OBSAssets/logos</code>) **คุณต้องกดปุ่ม แก้ไข ใน Popup เพื่อเปลี่ยนและบันทึกที่อยู่**",
        helpStep2: "2. กดปุ่ม <i class='fas fa-file-excel'></i> Excel เพื่อเลือกไฟล์ข้อมูล",
        helpStep3: "3. เลือก Match ID ที่ต้องการ แล้วกด <i class='fas fa-check'></i> Load",
        sourcesTitle: "OBS Sources ที่ต้องมี",
        sourcesTableHeaders: ["ชื่อ Source", "ประเภท Source", "รายละเอียด"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'สีทีม A (สีหลัก)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'สีทีม B (สีหลัก)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'สีทีม A (สีรอง)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'สีทีม B (สีรอง)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'โลโก้ทีม A' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'โลโก้ทีม B' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'ชื่อทีม A' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'ชื่อทีม B' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'คะแนนทีม A (หลัก)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'คะแนนทีม B (หลัก)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'คะแนน 2 ทีม A (ฟาวล์/แต้ม)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'คะแนน 2 ทีม B (ฟาวล์/แต้ม)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'ข้อความ Label 1' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'ข้อความ Label 2' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'ข้อความ Label 3' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'ครึ่งเวลา' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'ตัวนับเวลา' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'ทดเวลาบาดเจ็บ (+1)' },
        ],
        understand: "เข้าใจแล้ว",
        donateTitle: "ร่วมสนับสนุน",
        donateThai: "สำหรับคนไทย (ขึ้น Scoreboard)",
        donateForeign: "สำหรับนอกประเทศไทย",
        timeSettingsTitle: "ตั้งเวลาเริ่มต้น",
        timeSettingsMinutes: "นาที",
        timeSettingsSeconds: "วินาที",
        logoPathTitle: "ที่อยู่โฟลเดอร์โลโก้",
        logoPathDesc: "ที่อยู่โฟลเดอร์โลโก้ปัจจุบันคือ:",
        logoPathHint: "ตั้งค่าที่อยู่โฟลเดอร์โลโก้",
        changelogTitle: "ประวัติการอัปเดต",
        changelogContent: `
            <ul class="changelog-list">
                 <li>
                    <h5>เวอร์ชัน 2.6 (ล่าสุด)</h5>
                    <ul>
                        <li>**คีย์ลัดกำหนดเอง:** เพิ่มแผงตั้งค่าคีย์ลัดเพื่อปรับเปลี่ยนปุ่มควบคุมได้ตามต้องการ</li>
                        <li>**จัดการสีทีม:** เพิ่มปุ่มล้างหน่วยความจำสีทีมที่บันทึกไว้</li>
                        <li>**การแสดงผลคะแนน 2:** ย้ายการควบคุมไปที่หน้าต่างตั้งค่าหลักเพื่อความเสถียร</li>
                        <li>**ข้อความประกาศ:** โหลดจากไฟล์ <code>fcp_v2_assets/announcement.txt</code></li>
                        <li>**ฟีเจอร์:** เพิ่มปุ่มรีเซ็ตทั้งหมด (Full Reset) และ Global Key Listener</li>
                        <li>**UI:** ปรับปรุงตาราง Source ในหน้าช่วยเหลือให้สามารถคัดลอกชื่อได้ง่าย</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "โปรด Upload ไฟล์ก่อน",
        toastMatchNotFound: "ไม่พบ Match ID:",
        toastLoaded: "โหลด ID สำเร็จ:",
        toastSuccess: "สำเร็จ",
        toastSwapped: "สลับฝั่งทีมแล้ว",
        toastNoTextToCopy: "ไม่มีข้อความให้คัดลอก",
        toastCopied: "คัดลอกแล้ว",
        toastCopyFailed: "คัดลอกล้มเหลว",
        toastScoreReset: "รีเซ็ตคะแนนแล้ว",
        toastScore2Reset: "รีเซ็ตคะแนน 2 แล้ว",
        toastFullReset: "รีเซ็ตสกอร์บอร์ดทั้งหมดแล้ว",
        toastCopiedSourceName: "คัดลอกชื่อ Source แล้ว:",
        toastSaved: "บันทึกแล้ว",
        toastKeybindsSaved: "บันทึกคีย์ลัดแล้ว!", // NEW
        toastColorsCleared: "ล้างหน่วยความจำสีทีมแล้ว!", // NEW
        toastObsError: "เชื่อมต่อ OBS ไม่สำเร็จ",
        toastInvalidTime: "รูปแบบเวลาไม่ถูกต้อง กรุณาตรวจสอบนาทีและวินาที (0-59)",
        toastTimeSet: "ตั้งค่าและอัปเดตเวลาเริ่มต้นแล้ว",
    },
    // Lao
    lo: {
        appTitle: "ໂຕຄວບຄຸມກະດານຄະແນນບານເຕະ - V2.6",
        excel: "Excel",
        matchId: "ID:",
        load: "ໂຫຼດ",
        teamA: "ທີມ A",
        teamB: "ທີມ B",
        edit: "ແກ້ໄຂ",
        editHint: "ແກ້ໄຂຊື່ ຫຼື ເພີ່ມແຖວໃໝ່ດ້ວຍ /",
        ok: "ຕົກລົງ",
        label1: "ປ້າຍ 1",
        label2: "ປ້າຍ 2",
        label3: "ປ້າຍ 3",
        swap: "ສลับຝັ່ງ",
        reset: "ຣີເຊັດ",
        fullReset: "ຣີເຊັດທັງໝົດ",
        score2Label: "ຟາວ/ຄະແນນ 2",
        hide: "ເຊື່ອງ",
        show: "ສະແດງ",
        score2VisibilityGroup: "ຄວບຄຸມການສະແດງຄະແນນ 2",
        resetKeybinds: "ຣີເຊັດຄีย์ລັດ",
        resetColors: "ລ້າງໜ່ວຍຄວາມຈຳສີທີມ",
        half: "ເຄິ່ງ",
        injuryTime: "ທົດເວລາ",
        countdown: "ນັບຖອຍຫຼັງ",
        countdownHint: "ໂຕນັບເວລາຖອຍຫຼັງ",
        resetToZeroHint: "ຣີເຊັດເວລາເປັນ 00:00",
        resetToStartHint: "ຣີເຊັດເປັນເວລາເລີ່ມຕົ້ນທີ່ຕັ້ງໄວ້",
        settings: "ຕັ້ງຄ່າ",
        copy: "ສຳເນົາ",
        help: "ວິທີໃຊ້",
        donate: "ສະໜັບສະໜູນ",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "ອັບເດດເວີຊັ່ນ 2.6",
        detailsTitle: "ຕັ້ງຄ່າ & ຂໍ້ຄວາມປະກາດ",
        detailsDesc: "ປັບແຕ່ງການຕັ້ງຄ່າທົ່ວໄປດ້ານລຸ່ມ.",
        tagsTitle: "ແທັກທີ່ໃຊ້ໄດ້ສຳລັບຂໍ້ຄວາມປະກາດ",
        keybindsTitle: "ຕັ້ງຄ່າຄีย์ລັດ (Keyboard Shortcuts)",
        keybindsList: [
            { id: "scoreA_plus", label: "+ ຄະແນນ A (ຫຼັກ)", default: "1" },
            { id: "scoreA_minus", label: "- ຄະແນນ A (ຫຼັກ)", default: "2" },
            { id: "scoreB_plus", label: "+ ຄະແນນ B (ຫຼັກ)", default: "4" },
            { id: "scoreB_minus", label: "- ຄະແນນ B (ຫຼັກ)", default: "5" },
            { id: "score2A_plus", label: "+ ຄະແນນ A (ຮອງ)", default: "7" },
            { id: "score2A_minus", label: "- ຄະແນນ A (ຮອງ)", default: "8" },
            { id: "score2B_plus", label: "+ ຄະແນນ B (ຮອງ)", default: "9" },
            { id: "score2B_minus", label: "- ຄະແນນ B (ຮອງ)", default: "0" },
            { id: "timer_playpause", label: "ເລີ່ມ/ຢຸດ ເວລາ", default: " " },
            { id: "timer_resetstart", label: "ຣີເຊັດໄປເວລາເລີ່ມຕົ້ນ", default: "F10" },
            { id: "timer_togglehalf", label: "ສลับເຄິ່ງເວລາ", default: "F11" },
            { id: "full_reset", label: "ຣີເຊັດທັງໝົດ", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ຊື່ທີມ A' },
            { code: '&lt;TeamB&gt;', desc: '- ຊື່ທີມ B' },
            { code: '&lt;score_team_a&gt;', desc: '- ຄະແນນທີມ A' },
            { code: '&lt;score_team_b&gt;', desc: '- ຄະແນນທີມ B' },
            { code: '&lt;score2_team_a&gt;', desc: '- ຄະແນນ 2 ທີມ A (ຟາວ/ແຕ້ມ)' },
            { code: '&lt;score2_team_b&gt;', desc: '- ຄະແນນ 2 ທີມ B (ຟາວ/ແຕ້ມ)' },
            { code: '&lt;time_counter&gt;', desc: '- ເວລາປັດຈຸບັນ (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ເຄິ່ງເວລາ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 1' },
            { code: '&lt;label2&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 2' },
            { code: '&lt;label3&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 3' },
        ],
        save: "ບັນທຶກ",
        close: "ປິດ",
        saveAndUpdate: "ບັນທຶກ ແລະ ອັບເດດ",
        helpTitle: "ວິທີການໃຊ້ງານ",
        helpStep1: "1. ກົດໄອຄອນ <i class='fas fa-folder-open'></i> ເພື່ອຕັ້ງຄ່າທີ່ຢູ່ໂຟນເດີໂລໂກ້ (ຄ່າເລີ່ມຕົ້ນແມ່ນ <code>C:/OBSAssets/logos</code>). **ທ່ານຕ້ອງກົດປຸ່ມ ແກ້ໄຂ ພາຍໃນ Popup ເພື່ອປ່ຽນ ແລະ ບັນທຶກທີ່ຢູ່.**",
        helpStep2: "2. ກົດປຸ່ມ <i class='fas fa-file-excel'></i> Excel ເພື່ອເລືອກໄຟລ໌ຂໍ້ມູນ.",
        helpStep3: "3. ເລືອກ Match ID ທີ່ຕ້ອງການ ແລ້ວກົດ <i class='fas fa-check'></i> ໂຫຼດ.",
        sourcesTitle: "OBS Sources ທີ່ຕ້ອງມີ",
        sourcesTableHeaders: ["ຊື່ Source", "ປະເພດ Source", "ລາຍລະອຽດ"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'ສີທີມ A (ສີຫຼັກ)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'ສີທີມ B (ສີຫຼັກ)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'ສີທີມ A (ສີຮອງ)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'ສີທີມ B (ສີຮອງ)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'ໂລໂກ້ທີມ A' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'ໂລໂກ້ທີມ B' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'ຊື່ທີມ A' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'ຊື່ທີມ B' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'ຄະແນນທີມ A (ຫຼັກ)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'ຄະແນນທີມ B (ຫຼັກ)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'ຄະແນນ 2 ທີມ A (ຟາວ/ແຕ້ມ)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'ຄະແນນ 2 ທີມ B (ຟາວ/ແຕ້ມ)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'ຂໍ້ຄວາມປ້າຍ 1' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'ຂໍ້ຄວາມປ້າຍ 2' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'ຂໍ້ຄວາມປ້າຍ 3' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'ເຄິ່ງເວລາ' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'ໂຕນັບເວລາ' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'ທົດເວລາບາດເຈັບ (+1)' },
        ],
        understand: "ເຂົ້າໃຈແລ້ວ",
        donateTitle: "ຮ່ວມສະໜັບສະໜູນ",
        donateThai: "ສຳລັບຄົນໄທ (ຂຶ້ນ Scoreboard)",
        donateForeign: "ສຳລັບຕ່າງປະເທດ",
        timeSettingsTitle: "ຕັ້ງເວລາເລີ່ມຕົ້ນ",
        timeSettingsMinutes: "ນາທີ",
        timeSettingsSeconds: "ວິນາທີ",
        logoPathTitle: "ທີ່ຢູ່ໂຟນເດີໂລໂກ້",
        logoPathDesc: "ທີ່ຢູ່ໂຟນເດີໂລໂກ້ປັດຈຸບັນແມ່ນ:",
        logoPathHint: "ຕັ້ງຄ່າທີ່ຢູ່ໂຟນເດີໂລໂກ້",
        changelogTitle: "ປະຫວັດການອັບເດດ",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>ເວີຊັ່ນ 2.6 (ລ່າສຸດ)</h5>
                    <ul>
                        <li>**ຄีย์ລັດກຳນົດເອງ:** ເພີ່ມແຜງຕັ້ງຄ່າຄีย์ລັດເພື່ອປັບປ່ຽນປຸ່ມຄວບຄຸມໄດ້ຕາມຕ້ອງການ.</li>
                        <li>**ຈັດການສີທີມ:** ເພີ່ມປຸ່ມລ້າງໜ່ວຍຄວາມຈຳສີທີມທີ່ບັນທຶກໄວ້.</li>
                        <li>**ການສະແດງຜົນຄະແນນ 2:** ຍ້າຍການຄວບຄຸມໄປທີ່ໜ້າຕ່າງຕັ້ງຄ່າຫຼັກເພື່ອຄວາມສະຖຽນ.</li>
                        <li>**ຂໍ້ຄວາມປະກາດ:** ໂຫຼດຈາກໄຟລ໌ <code>fcp_v2_assets/announcement.txt</code>.</li>
                        <li>**ຄຸນສົມບັດ:** ເພີ່ມປຸ່ມຣີເຊັດທັງໝົດ (Full Reset) ແລະ Global Key Listener.</li>
                        <li>**UI:** ປັບປຸງຕາຕະລາງ Source ໃນໜ້າຊ່ວຍເຫຼືອໃຫ້ສາມາດສຳເນົາຊື່ໄດ້ງ່າຍ.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "ກະລຸນາອັບໂຫຼດໄຟລ໌ກ່ອນ",
        toastMatchNotFound: "ບໍ່ພົບ Match ID:",
        toastLoaded: "ໂຫຼດ ID ສຳເລັດ:",
        toastSuccess: "ສຳເລັດ",
        toastSwapped: "ສลับຝັ່ງທີມແລ້ວ",
        toastNoTextToCopy: "ບໍ່ມີຂໍ້ຄວາມໃຫ້ສຳເນົາ",
        toastCopied: "ສຳເນົາແລ້ວ",
        toastCopyFailed: "ສຳເນົາລົ້ມເຫຼວ",
        toastScoreReset: "ຣີເຊັດຄະແນນແລ້ວ",
        toastScore2Reset: "ຣີເຊັດຄະແນນ 2 ແລ້ວ",
        toastFullReset: "ຣີເຊັດກະດານຄະແນນທັງໝົດແລ້ວ",
        toastCopiedSourceName: "ສຳເນົາຊື່ Source ແລ້ວ:",
        toastSaved: "ບັນທຶກແລ້ວ",
        toastKeybindsSaved: "ບັນທຶກຄีย์ລັດແລ້ວ!",
        toastColorsCleared: "ລ້າງໜ່ວຍຄວາມຈຳສີທີມແລ້ວ!",
        toastObsError: "ເຊື່ອມຕໍ່ OBS ບໍ່ສຳເລັດ",
        toastInvalidTime: "ຮູບແບບເວລາບໍ່ຖືກຕ້ອງ. ກະລຸນາກວດສອບນາທີ ແລະ ວິນາທີ (0-59).",
        toastTimeSet: "ໄດ້ຕັ້ງ ແລະ ອັບເດດເວລາເລີ່ມຕົ້ນແລ້ວ.",
    },
    // Korean
    ko: {
        appTitle: "축구 스코어보드 컨트롤러 - V2.6",
        excel: "엑셀",
        matchId: "ID:",
        load: "로드",
        teamA: "팀 A",
        teamB: "팀 B",
        edit: "수정",
        editHint: "이름을 수정하거나 /로 새 줄을 추가하세요",
        ok: "확인",
        label1: "레이블 1",
        label2: "레이블 2",
        label3: "레이블 3",
        swap: "팀 교체",
        reset: "재설정",
        fullReset: "전체 재설정",
        score2Label: "파울/점수 2",
        hide: "숨기기",
        show: "표시",
        score2VisibilityGroup: "점수 2 표시 제어",
        resetKeybinds: "키보드 단축키 재설정",
        resetColors: "팀 색상 메모리 지우기",
        half: "전/후반",
        injuryTime: "추가 시간",
        countdown: "카운트다운",
        countdownHint: "카운트다운 타이머",
        resetToZeroHint: "타이머를 00:00으로 재설정",
        resetToStartHint: "구성된 시작 시간으로 타이머 재설정",
        settings: "설정",
        copy: "복사",
        help: "도움말",
        donate: "후원",
        footerAppName: "OBS Dock UI 스코어보드",
        changelog: "업데이트 버전 2.6",
        detailsTitle: "설정 및 공지",
        detailsDesc: "아래에서 일반 설정을 사용자 지정합니다.",
        tagsTitle: "공지사항에 사용 가능한 태그",
        keybindsTitle: "사용자 지정 키보드 단축키",
        keybindsList: [
            { id: "scoreA_plus", label: "+ 점수 A (메인)", default: "1" },
            { id: "scoreA_minus", label: "- 점수 A (메인)", default: "2" },
            { id: "scoreB_plus", label: "+ 점수 B (메인)", default: "4" },
            { id: "scoreB_minus", label: "- 점수 B (메인)", default: "5" },
            { id: "score2A_plus", label: "+ 점수 A (보조)", default: "7" },
            { id: "score2A_minus", label: "- 점수 A (보조)", default: "8" },
            { id: "score2B_plus", label: "+ 점수 B (보조)", default: "9" },
            { id: "score2B_minus", label: "- 점수 B (보조)", default: "0" },
            { id: "timer_playpause", label: "타이머 시작/정지", default: " " },
            { id: "timer_resetstart", label: "시작 시간으로 재설정", default: "F10" },
            { id: "timer_togglehalf", label: "전/후반 전환", default: "F11" },
            { id: "full_reset", label: "전체 재설정", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- 팀 A 이름' },
            { code: '&lt;TeamB&gt;', desc: '- 팀 B 이름' },
            { code: '&lt;score_team_a&gt;', desc: '- 팀 A 점수' },
            { code: '&lt;score_team_b&gt;', desc: '- 팀 B 점수' },
            { code: '&lt;score2_team_a&gt;', desc: '- 팀 A 점수 2 (파울/횟수)' },
            { code: '&lt;score2_team_b&gt;', desc: '- 팀 B 점수 2 (파울/횟수)' },
            { code: '&lt;time_counter&gt;', desc: '- 현재 시간 (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- 전/후반 (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- 레이블 1 텍스트' },
            { code: '&lt;label2&gt;', desc: '- 레이블 2 텍스트' },
            { code: '&lt;label3&gt;', desc: '- 레이블 3 텍스트' },
        ],
        save: "저장",
        close: "닫기",
        saveAndUpdate: "저장 및 업데이트",
        helpTitle: "사용 방법",
        helpStep1: "1. <i class='fas fa-folder-open'></i> 아이콘을 클릭하여 로고 폴더 경로를 설정하세요. 기본값은 <code>C:/OBSAssets/logos</code>입니다. **경로를 변경하고 저장하려면 팝업 내에서 수정 버튼을 클릭해야 합니다.**",
        helpStep2: "2. <i class='fas fa-file-excel'></i> 엑셀 버튼을 클릭하여 데이터 파일을 선택하세요。",
        helpStep3: "3. 원하는 경기 ID를 선택하고 <i class='fas fa-check'></i> 로드를 클릭하세요。",
        sourcesTitle: "필요한 OBS 소스",
        sourcesTableHeaders: ["소스 이름", "소스 유형", "세부 정보"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: '팀 A (기본 색상)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: '팀 B (기본 색상)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: '팀 A (보조 색상)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: '팀 B (보조 색상)' },
            { code: 'logo_team_a', type: 'Image Source', desc: '팀 A 로고' },
            { code: 'logo_team_b', type: 'Image Source', desc: '팀 B 로고' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: '팀 A 이름' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: '팀 B 이름' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: '팀 A 점수 (메인)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: '팀 B 점수 (메인)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: '팀 A 점수 2 (파울/횟수)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: '팀 B 점수 2 (파울/횟수)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: '레이블 1 텍스트' },
            { code: 'label_2', type: 'Text (GDI+)', desc: '레이블 2 텍스트' },
            { code: 'label_3', type: 'Text (GDI+)', desc: '레이블 3 텍스트' },
            { code: 'half_text', type: 'Text (GDI+)', desc: '전/후반' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: '타이머' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: '추가 시간 (+1)' },
        ],
        understand: "이해했습니다",
        donateTitle: "후원하기",
        donateThai: "태국인을 위해 (스코어보드용)",
        donateForeign: "외국인용 (태국 외)",
        timeSettingsTitle: "시작 시간 설정",
        timeSettingsMinutes: "분",
        timeSettingsSeconds: "초",
        logoPathTitle: "로고 폴더 경로",
        logoPathDesc: "현재 로고 폴더 경로는 다음과 같습니다:",
        logoPathHint: "로고 폴더 경로 설정",
        changelogTitle: "업데이트 내역",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>버전 2.6 (최신)</h5>
                    <ul>
                        <li>**사용자 지정 키보드 단축키:** 키보드 단축키를 사용자 지정할 수 있는 설정 패널을 추가했습니다.</li>
                        <li>**팀 색상 관리:** 저장된 팀 색상 메모리를 지우는 옵션을 추가했습니다.</li>
                        <li>**점수 2 표시:** 안정적인 숨기기/표시를 위해 제어 기능을 주 설정 창으로 옮겼습니다.</li>
                        <li>**공지 사항:** <code>fcp_v2_assets/announcement.txt</code> 파일에서 로드됩니다.</li>
                        <li>**기능:** 전체 재설정 및 글로벌 키 리스너 제어 기능 추가.</li>
                        <li>**UI:** 도움말 소스 목록을 복사하기 쉬운 테이블 형식으로 개선했습니다.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "먼저 파일을 업로드하세요",
        toastMatchNotFound: "경기 ID를 찾을 수 없습니다:",
        toastLoaded: "ID 로드 성공:",
        toastSuccess: "성공",
        toastSwapped: "팀이 교체되었습니다",
        toastNoTextToCopy: "복사할 텍스트가 없습니다",
        toastCopied: "클립보드에 복사됨",
        toastCopyFailed: "복사 실패",
        toastScoreReset: "점수 재설정됨",
        toastScore2Reset: "점수 2 재설정됨",
        toastFullReset: "스코어보드 전체 재설정됨",
        toastCopiedSourceName: "소스 이름 복사됨:",
        toastSaved: "저장됨",
        toastKeybindsSaved: "키보드 단축키가 저장되었습니다!",
        toastColorsCleared: "팀 색상 메모리가 지워졌습니다!",
        toastObsError: "OBS 연결 실패",
        toastInvalidTime: "잘못된 시간 형식입니다. 분과 초(0-59)를 확인하세요。",
        toastTimeSet: "시작 시간이 설정 및 업데이트되었습니다。",
    },
    // Khmer (Cambodian)
    km: {
        appTitle: "កម្មវិធីបញ្ជាតារាងពិន្ទុបាល់ទាត់ - V2.6",
        excel: "Excel",
        matchId: "ID:",
        load: "ផ្ទុក",
        teamA: "ក្រុម A",
        teamB: "ក្រុម B",
        edit: "កែសម្រួល",
        editHint: "កែឈ្មោះ ឬបន្ថែមបន្ទាត់ថ្មីជាមួយ /",
        ok: "យល់ព្រម",
        label1: "ស្លាក ១",
        label2: "ស្លាក ២",
        label3: "ស្លាក ៣",
        swap: "ប្តូរក្រុម",
        reset: "កំណត់ឡើងវិញ",
        fullReset: "កំណត់ឡើងវិញទាំងអស់",
        score2Label: "ហ្វូល/ពិន្ទុ ២",
        hide: "លាក់",
        show: "បង្ហាញ",
        score2VisibilityGroup: "គ្រប់គ្រងការបង្ហាញពិន្ទុ 2",
        resetKeybinds: "កំណត់ផ្លូវកាត់ឡើងវិញ",
        resetColors: "លុបសតិពណ៌ក្រុម",
        half: "តង់",
        injuryTime: "ម៉ោងបន្ថែម",
        countdown: "រាប់ថយក្រោយ",
        countdownHint: "កម្មវិធីកំណត់เวลារាប់ថយក្រោយ",
        resetToZeroHint: "កំណត់ពេលវេលាឡើងវិញទៅ 00:00",
        resetToStartHint: "កំណត់ពេលវេលាឡើងវិញទៅពេលចាប់ផ្តើមដែលបានកំណត់",
        settings: "ការកំណត់",
        copy: "ចម្លង",
        help: "ជំនួយ",
        donate: "គាំទ្រ",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "អัปដេតកំណែ 2.6",
        detailsTitle: "ការកំណត់ និងការប្រកាស",
        detailsDesc: "ប្ដូរការកំណត់ទូទៅខាងក្រោមតាមតម្រូវការ។",
        tagsTitle: "ស្លាកដែលមានសម្រាប់ការប្រកាស",
        keybindsTitle: "ផ្លូវកាត់ក្តារចុចផ្ទាល់ខ្លួន (Keyboard Shortcuts)",
        keybindsList: [
            { id: "scoreA_plus", label: "+ ពិន្ទុ A (ចម្បង)", default: "1" },
            { id: "scoreA_minus", label: "- ពិន្ទុ A (ចម្បង)", default: "2" },
            { id: "scoreB_plus", label: "+ ពិន្ទុ B (ចម្បង)", default: "4" },
            { id: "scoreB_minus", label: "- ពិន្ទុ B (ចម្បង)", default: "5" },
            { id: "score2A_plus", label: "+ ពិន្ទុ A (បន្ទាប់បន្សំ)", default: "7" },
            { id: "score2A_minus", label: "- ពិន្ទុ A (បន្ទាប់បន្សំ)", default: "8" },
            { id: "score2B_plus", label: "+ ពិន្ទុ B (បន្ទាប់បន្សំ)", default: "9" },
            { id: "score2B_minus", label: "- ពិន្ទុ B (បន្ទាប់បន្សំ)", default: "0" },
            { id: "timer_playpause", label: "ចាប់ផ្ដើម/ផ្អាក ម៉ោង", default: " " },
            { id: "timer_resetstart", label: "កំណត់ម៉ោងចាប់ផ្ដើមឡើងវិញ", default: "F10" },
            { id: "timer_togglehalf", label: "ប្ដូរតង់", default: "F11" },
            { id: "full_reset", label: "កំណត់ឡើងវិញទាំងអស់", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ឈ្មោះក្រុម A' },
            { code: '&lt;TeamB&gt;', desc: '- ឈ្មោះក្រុម B' },
            { code: '&lt;score_team_a&gt;', desc: '- ពិន្ទុក្រុម A' },
            { code: '&lt;score_team_b&gt;', desc: '- ពិន្ទុក្រុម B' },
            { code: '&lt;score2_team_a&gt;', desc: '- ពិន្ទុ 2 ក្រុម A (ហ្វូល/រាប់)' },
            { code: '&lt;score2_team_b&gt;', desc: '- ពិន្ទុ 2 ក្រុម B (ហ្វូល/រាប់)' },
            { code: '&lt;time_counter&gt;', desc: '- ពេលវេលាបច្ចុប្បន្ន (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- តង់ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- អត្ថបទស្លាក ១' },
            { code: '&lt;label2&gt;', desc: '- អត្ថបទស្លាក ២' },
            { code: '&lt;label3&gt;', desc: '- អត្ថបទស្លាក ៣' },
        ],
        save: "រក្សាទុក",
        close: "បិទ",
        saveAndUpdate: "រក្សាទុក & ធ្វើបច្ចុប្បន្នភាព",
        helpTitle: "របៀបប្រើ",
        helpStep1: "1. ចុចរូបតំណាង <i class='fas fa-folder-open'></i> ដើម្បីកំណត់ផ្លូវថតនិមិត្តសញ្ញារបស់អ្នក។ តាមលំនាំដើមវាគឺ <code>C:/OBSAssets/logos</code>។ **អ្នកត្រូវចុចប៊ូតុង កែសម្រួល ក្នុង Popup ដើម្បីផ្លាស់ប្តូរ និងរក្សាទុកផ្លូវ។**",
        helpStep2: "2. ចុចប៊ូតុង <i class='fas fa-file-excel'></i> Excel ដើម្បីជ្រើសរើសឯកសារទិន្នន័យ។",
        helpStep3: "3. ជ្រើសរើស Match ID ដែលចង់បាន ហើយចុច <i class='fas fa-check'></i> ផ្ទុក។",
        sourcesTitle: "OBS Sources ដែលត្រូវការ",
        sourcesTableHeaders: ["ឈ្មោះ Source", "ប្រភេទ Source", "លម្អិត"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'ក្រុម A (ពណ៌ចម្បង)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'ក្រុម B (ពណ៌ចម្បង)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'ក្រុម A (ពណ៌បន្ទាប់បន្សំ)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'ក្រុម B (ពណ៌បន្ទាប់បន្សំ)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'និមិត្តសញ្ញាក្រុម A' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'និមិត្តសញ្ញាក្រុម B' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'ឈ្មោះក្រុម A' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'ឈ្មោះក្រុម B' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'ពិន្ទុក្រុម A (ចម្បង)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'ពិន្ទុក្រុម B (ចម្បង)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'ពិន្ទុ 2 ក្រុម A (ហ្វូល/រាប់)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'ពិន្ទុ 2 ក្រុម B (ហ្វូល/រាប់)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'ស្លាក ១' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'ស្លាក ២' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'ស្លាក ៣' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'តង់' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'កម្មវិធីកំណត់ពេល' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'ម៉ោងបន្ថែម (+1)' },
        ],
        understand: "យល់ហើយ",
        donateTitle: "គាំទ្រពួកយើង",
        donateThai: "សម្រាប់ជនជាតិថៃ (សម្រាប់តារាងពិន្ទុ)",
        donateForeign: "សម្រាប់ជនបរទេស (ក្រៅប្រទេសថៃ)",
        timeSettingsTitle: "កំណត់ម៉ោងចាប់ផ្តើម",
        timeSettingsMinutes: "នាទី",
        timeSettingsSeconds: "វិនាទី",
        logoPathTitle: "ផ្លូវថតនិមិត្តសញ្ញា",
        logoPathDesc: "ផ្លូវថតនិមិត្តសញ្ញាបច្ចុប្បន្នគឺ៖",
        logoPathHint: "កំណត់ផ្លូវថតនិមិត្តសញ្ញា",
        changelogTitle: "ប្រវត្តិធ្វើបច្ចុប្បន្នភាព",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>ជំនាន់ 2.6 (ថ្មីបំផុត)</h5>
                    <ul>
                        <li>**ផ្លូវកាត់ផ្ទាល់ខ្លួន:** បានបន្ថែមផ្ទាំងកំណត់ផ្លូវកាត់ក្តារចុចដើម្បីប្ដូរការគ្រប់គ្រងតាមតម្រូវការ។</li>
                        <li>**ការគ្រប់គ្រងពណ៌ក្រុម:** បានបន្ថែមជម្រើសលុបសតិពណ៌ក្រុមដែលបានរក្សាទុក។</li>
                        <li>**ការបង្ហាញពិន្ទុ 2:** ការគ្រប់គ្រងត្រូវបានផ្លាស់ទៅបង្អួចកំណត់សំខាន់សម្រាប់ការលាក់/បង្ហាញដែលមានស្ថេរភាព។</li>
                        <li>**ការប្រកាស:** ផ្ទុកពីឯកសារ <code>fcp_v2_assets/announcement.txt</code>។</li>
                        <li>**លក្ខណៈពិសេស:** បានបន្ថែមការកំណត់ឡើងវិញទាំងស្រុង និងការគ្រប់គ្រង Global Key Listener។</li>
                        <li>**UI:** បានកែលម្អ Sources ជំនួយទៅជាទម្រង់តារាងដែលងាយស្រួលចម្លង។</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "សូមអាប់ឡូតឯកសារជាមុនសិន",
        toastMatchNotFound: "រកមិនឃើញ Match ID:",
        toastLoaded: "បានផ្ទុក ID:",
        toastSuccess: "ជោគជ័យ",
        toastSwapped: "បានប្តូរក្រុម",
        toastNoTextToCopy: "គ្មានអត្ថបទសម្រាប់ចម្លង",
        toastCopied: "បានចម្លងទៅក្ដារតម្បៀតខ្ទាស់",
        toastCopyFailed: "ការចម្លងបានបរាជ័យ",
        toastScoreReset: "បានកំណត់ពិន្ទុឡើងវិញ",
        toastScore2Reset: "បានកំណត់ពិន្ទុ 2 ឡើងវិញ",
        toastFullReset: "បានកំណត់តារាងពិន្ទុឡើងវិញទាំងអស់",
        toastCopiedSourceName: "បានចម្លងឈ្មោះ Source:",
        toastSaved: "បានរក្សាទុក",
        toastKeybindsSaved: "បានរក្សាទុកផ្លូវកាត់ក្តារចុចហើយ!",
        toastColorsCleared: "បានលុបសតិពណ៌ក្រុមហើយ!",
        toastObsError: "ការភ្ជាប់ទៅ OBS បានបរាជ័យ",
        toastInvalidTime: "ទម្រង់ម៉ោងមិនត្រឹមត្រូវ។ សូមពិនិត្យមើលនាទី និងវិនាទី (0-59)។",
        toastTimeSet: "បានកំណត់ម៉ោងចាប់ផ្តើម និងធ្វើបច្ចុប្បន្នភាពហើយ។",
    },
    // Japanese
    jp: {
        appTitle: "サッカー スコアボード コントローラー - V2.6",
        excel: "エクセル",
        matchId: "ID:",
        load: "ロード",
        teamA: "チーム A",
        teamB: "チーム B",
        edit: "編集",
        editHint: "名前を編集するか、/で改行を追加",
        ok: "OK",
        label1: "ラベル 1",
        label2: "ラベル 2",
        label3: "ラベル 3",
        swap: "チーム入替",
        reset: "リセット",
        fullReset: "全リセット",
        score2Label: "ファウル/カウント 2",
        hide: "非表示",
        show: "表示",
        score2VisibilityGroup: "スコア 2 表示制御",
        resetKeybinds: "キーバインドをリセット",
        resetColors: "チームカラーメモリをクリア",
        half: "ハーフ",
        injuryTime: "追加時間",
        countdown: "カウントダウン",
        countdownHint: "カウントダウン タイマー",
        resetToZeroHint: "タイマーを 00:00 にリセット",
        resetToStartHint: "設定された開始時間にタイマーをリセット",
        settings: "設定",
        copy: "コピー",
        help: "ヘルプ",
        donate: "寄付",
        footerAppName: "OBS Dock UI スコアボード",
        changelog: "更新バージョン 2.6",
        detailsTitle: "設定とアナウンス",
        detailsDesc: "以下の一般設定をカスタマイズします。",
        tagsTitle: "アナウンスに利用可能なタグ",
        keybindsTitle: "カスタムキーボードショートカット",
        keybindsList: [
            { id: "scoreA_plus", label: "+ スコア A (メイン)", default: "1" },
            { id: "scoreA_minus", label: "- スコア A (メイン)", default: "2" },
            { id: "scoreB_plus", label: "+ スコア B (メイン)", default: "4" },
            { id: "scoreB_minus", label: "- スコア B (メイン)", default: "5" },
            { id: "score2A_plus", label: "+ スコア A (サブ)", default: "7" },
            { id: "score2A_minus", label: "- スコア A (サブ)", default: "8" },
            { id: "score2B_plus", label: "+ スコア B (サブ)", default: "9" },
            { id: "score2B_minus", label: "- スコア B (サブ)", default: "0" },
            { id: "timer_playpause", label: "タイマー再生/一時停止", default: " " },
            { id: "timer_resetstart", label: "開始時間にリセット", default: "F10" },
            { id: "timer_togglehalf", label: "ハーフ切り替え", default: "F11" },
            { id: "full_reset", label: "全リセット", default: "F12" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- チーム A 名' },
            { code: '&lt;TeamB&gt;', desc: '- チーム B 名' },
            { code: '&lt;score_team_a&gt;', desc: '- チーム A スコア' },
            { code: '&lt;score_team_b&gt;', desc: '- チーム B スコア' },
            { code: '&lt;score2_team_a&gt;', desc: '- チーム A スコア 2 (ファウル/カウント)' },
            { code: '&lt;score2_team_b&gt;', desc: '- チーム B スコア 2 (ファウル/カウント)' },
            { code: '&lt;time_counter&gt;', desc: '- 現在時刻 (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ハーフ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ラベル 1 テキスト' },
            { code: '&lt;label2&gt;', desc: '- ラベル 2 テキスト' },
            { code: '&lt;label3&gt;', desc: '- ラベル 3 テキスト' },
        ],
        save: "保存",
        close: "閉じる",
        saveAndUpdate: "保存して更新",
        helpTitle: "使用方法",
        helpStep1: "1. <i class='fas fa-folder-open'></i> アイコンをクリックしてロゴフォルダのパスを設定します。デフォルトは <code>C:/OBSAssets/logos</code> です。**ポップアップ内の編集ボタンをクリックしてパスを変更し、保存する必要があります。**",
        helpStep2: "2. <i class='fas fa-file-excel'></i> Excel ボタンをクリックしてデータファイルを選択します。",
        helpStep3: "3. 目的の試合 ID を選択し、<i class='fas fa-check'></i> ロードをクリックします。",
        sourcesTitle: "必要な OBS ソース",
        sourcesTableHeaders: ["ソース名", "ソースタイプ", "詳細"],
        sourcesList: [
            { code: 'Color_Team_A', type: 'カラーソース', desc: 'チーム A (メインカラー)' },
            { code: 'Color_Team_B', type: 'カラーソース', desc: 'チーム B (メインカラー)' },
            { code: 'Color_Team_A_2', type: 'カラーソース', desc: 'チーム A (サブカラー)' },
            { code: 'Color_Team_B_2', type: 'カラーソース', desc: 'チーム B (サブカラー)' },
            { code: 'logo_team_a', type: '画像ソース', desc: 'チーム A ロゴ' },
            { code: 'logo_team_b', type: '画像ソース', desc: 'チーム B ロゴ' },
            { code: 'name_team_a', type: 'テキスト (GDI+)', desc: 'チーム A 名' },
            { code: 'name_team_b', type: 'テキスト (GDI+)', desc: 'チーム B 名' },
            { code: 'score_team_a', type: 'テキスト (GDI+)', desc: 'チーム A スコア (メイン)' },
            { code: 'score_team_b', type: 'テキスト (GDI+)', desc: 'チーム B スコア (メイン)' },
            { code: 'score2_team_a', type: 'テキスト (GDI+)', desc: 'チーム A スコア 2 (ファウル/カウント)' },
            { code: 'score2_team_b', type: 'テキスト (GDI+)', desc: 'チーム B スコア 2 (ファウル/カウント)' },
            { code: 'label_1', type: 'テキスト (GDI+)', desc: 'ラベル 1 テキスト' },
            { code: 'label_2', type: 'テキスト (GDI+)', desc: 'ラベル 2 テキスト' },
            { code: 'label_3', type: 'テキスト (GDI+)', desc: 'ラベル 3 テキスト' },
            { code: 'half_text', type: 'テキスト (GDI+)', desc: 'ハーフ' },
            { code: 'time_counter', type: 'テキスト (GDI+)', desc: 'タイマー' },
            { code: 'injury_time_text', type: 'テキスト (GDI+)', desc: '追加時間 (+1)' },
        ],
        understand: "了解",
        donateTitle: "サポート",
        donateThai: "タイ在住者向け (スコアボード用)",
        donateForeign: "海外在住者向け",
        timeSettingsTitle: "開始時間設定",
        timeSettingsMinutes: "分",
        timeSettingsSeconds: "秒",
        logoPathTitle: "ロゴフォルダ パス",
        logoPathDesc: "現在のロゴフォルダ パス:",
        logoPathHint: "ロゴフォルダ パスを設定",
        changelogTitle: "更新履歴",
        changelogContent: `
            <ul class="changelog-list">
                <li><h5>バージョン 2.6 (最新)</h5>
                    <ul>
                        <li>**カスタムキーボードショートカット:** キーボードショートカットをカスタマイズできる設定パネルを追加しました。</li>
                        <li>**チームカラー管理:** 保存されたチームカラーメモリをクリアするオプションを追加しました。</li>
                        <li>**スコア 2 表示:** 安定した非表示/表示のために、制御機能をメイン設定ウィンドウに移動しました。</li>
                        <li>**アナウンス:** <code>fcp_v2_assets/announcement.txt</code> ファイルからロードされます。</li>
                        <li>**機能:** 全リセットとグローバルキーリスナー制御機能を追加しました。</li>
                        <li>**UI:** ヘルプソースリストをコピーしやすいテーブル形式に改善しました。</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst: "まずファイルをアップロードしてください",
        toastMatchNotFound: "試合 ID が見つかりません:",
        toastLoaded: "ID ロード完了:",
        toastSuccess: "成功",
        toastSwapped: "チームが入れ替わりました",
        toastNoTextToCopy: "コピーするテキストがありません",
        toastCopied: "クリップボードにコピーされました",
        toastCopyFailed: "コピーに失敗しました",
        toastScoreReset: "スコアがリセットされました",
        toastScore2Reset: "スコア 2 がリセットされました",
        toastFullReset: "スコアボードが完全にリセットされました",
        toastCopiedSourceName: "ソース名をコピーしました:",
        toastSaved: "保存されました",
        toastKeybindsSaved: "キーボードショートカットが保存されました!",
        toastColorsCleared: "チームカラーメモリがクリアされました!",
        toastObsError: "OBS への接続に失敗しました",
        toastInvalidTime: "無効な時刻形式です。分と秒 (0-59) を確認してください。",
        toastTimeSet: "開始時間が設定され、更新されました。",
    },
};