// fcp_v2_assets/languages.js
// ไฟล์สำหรับเก็บคำแปลทั้งหมด

export const translations = {
    // English
    en: {
        appTitle: "Football Scoreboard Controller - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "Load",
        teamA: "Team A",
        teamB: "Team B",
        editHint: "Edit name or add new line with /",
        ok: "OK",
        label1: "Label 1",
        label2: "Label 2",
        label3: "Label 3",
        swap: "Swap Teams",
        reset: "Reset",
        half: "Half",
        injuryTime: "Added Time",
        countdown: "Down",
        countdownHint: "Countdown Timer",
        settings: "Settings",
        copy: "Copy",
        help: "Help",
        donate: "Donate",
        version: "OBS Dock UI Scoreboard - Version 2.2",
        detailsTitle: "Announcement Text Settings",
        detailsDesc: "Create message using the tags below to pull data automatically.",
        tagsTitle: "Available Tags",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Team A Name' },
            { code: '&lt;TeamB&gt;', desc: '- Team B Name' },
            { code: '&lt;score_team_a&gt;', desc: '- Team A Score' },
            { code: '&lt;score_team_b&gt;', desc: '- Team B Score' },
            { code: '&lt;time_counter&gt;', desc: '- Current Time (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Half (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Label 1 Text' },
            { code: '&lt;label2&gt;', desc: '- Label 2 Text' },
            { code: '&lt;label3&gt;', desc: '- Label 3 Text' },
        ],
        save: "Save",
        close: "Close",
        helpTitle: "How to Use",
        helpStep1: "1. Place all logo files in <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. Click <i class='fas fa-file-excel'></i> Excel button to select data file.",
        helpStep3: "3. Select the desired Match ID and click <i class='fas fa-check'></i> Load.",
        sourcesTitle: "Required OBS Sources",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** for Team A' },
            { code: 'Color_Team_B', desc: '- **Color Source** for Team B' },
            { code: 'logo_team_a', desc: '- **Image Source** for Team A Logo' },
            { code: 'logo_team_b', desc: '- **Image Source** for Team B Logo' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** for Team A Name' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** for Team B Name' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** for Team A Score' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** for Team B Score' },
            { code: 'label_1/2/3', desc: '- Text (GDI+) for Labels' },
            { code: 'half_text', desc: '- Text (GDI+) for Half' },
            { code: 'time_counter', desc: '- Text (GDI+) for Timer' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** for Added Time (+1)' },
        ],
        understand: "Got it",
        donateTitle: "Support Us",
        donateThai: "For Thais (for Scoreboard)",
        donateForeign: "For Foreigners (Outside Thailand)",
        toastLoadFileFirst: "Please upload a file first",
        toastMatchNotFound: "Match ID not found:",
        toastLoaded: "Loaded ID:",
        toastSuccess: "Success",
        toastSwapped: "Teams swapped",
        toastNoTextToCopy: "No text to copy",
        toastCopied: "Copied to clipboard",
        toastCopyFailed: "Copy failed",
        toastScoreReset: "Score reset",
        toastSaved: "Saved",
        toastObsError: "Failed to connect to OBS",
    },
    // ภาษาไทย
    th: {
        appTitle: "โปรแกรมควบคุมสกอร์บอร์ดฟุตบอล - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "โหลด",
        teamA: "ทีม A",
        teamB: "ทีม B",
        editHint: "แก้ไขชื่อ หรือขึ้นบรรทัดใหม่ด้วยการใส่ /",
        ok: "ตกลง",
        label1: "ป้าย 1",
        label2: "ป้าย 2",
        label3: "ป้าย 3",
        swap: "สลับฝั่ง",
        reset: "รีเซ็ต",
        half: "ครึ่ง",
        injuryTime: "ทดเวลา",
        countdown: "นับถอยหลัง",
        countdownHint: "ตัวนับเวลาถอยหลัง",
        settings: "ตั้งค่า",
        copy: "คัดลอก",
        help: "วิธีใช้",
        donate: "สนับสนุน",
        version: "OBS Dock UI Scoreboard - เวอร์ชั่น 2.3",
        detailsTitle: "ตั้งค่าข้อความประกาศ",
        detailsDesc: "สร้างข้อความโดยใช้ Tags ด้านล่างเพื่อดึงข้อมูลอัตโนมัติ",
        tagsTitle: "Tags ที่ใช้งานได้",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ชื่อทีม A' },
            { code: '&lt;TeamB&gt;', desc: '- ชื่อทีม B' },
            { code: '&lt;score_team_a&gt;', desc: '- คะแนนทีม A' },
            { code: '&lt;score_team_b&gt;', desc: '- คะแนนทีม B' },
            { code: '&lt;time_counter&gt;', desc: '- เวลาปัจจุบัน (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ครึ่งเวลา (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ข้อความ Label 1' },
            { code: '&lt;label2&gt;', desc: '- ข้อความ Label 2' },
            { code: '&lt;label3&gt;', desc: '- ข้อความ Label 3' },
        ],
        save: "บันทึก",
        close: "ปิด",
        helpTitle: "วิธีการใช้งาน",
        helpStep1: "1. นำไฟล์โลโก้ทั้งหมดไปไว้ที่ <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. กดปุ่ม <i class='fas fa-file-excel'></i> Excel เพื่อเลือกไฟล์ข้อมูล",
        helpStep3: "3. เลือก Match ID ที่ต้องการ แล้วกด <i class='fas fa-check'></i> Load",
        sourcesTitle: "OBS Sources ที่ต้องมี",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** สำหรับสีทีม A' },
            { code: 'Color_Team_B', desc: '- **Color Source** สำหรับสีทีม B' },
            { code: 'logo_team_a', desc: '- **Image Source** สำหรับโลโก้ทีม A' },
            { code: 'logo_team_b', desc: '- **Image Source** สำหรับโลโก้ทีม B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** สำหรับชื่อทีม A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** สำหรับชื่อทีม B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** สำหรับคะแนนทีม A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** สำหรับคะแนนทีม B' },
            { code: 'label_1/2/3', desc: '- Text (GDI+) ป้ายกำกับต่างๆ' },
            { code: 'half_text', desc: '- Text (GDI+) ครึ่งเวลา' },
            { code: 'time_counter', desc: '- Text (GDI+) ตัวนับเวลา' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** สำหรับทดเวลาบาดเจ็บ (+1)' },
        ],
        understand: "เข้าใจแล้ว",
        donateTitle: "ร่วมสนับสนุน",
        donateThai: "สำหรับคนไทย (ขึ้น Scoreboard)",
        donateForeign: "สำหรับนอกประเทศไทย",
        toastLoadFileFirst: "โปรด Upload ไฟล์ก่อน",
        toastMatchNotFound: "ไม่พบ Match ID:",
        toastLoaded: "โหลด ID สำเร็จ:",
        toastSuccess: "สำเร็จ",
        toastSwapped: "สลับฝั่งทีมแล้ว",
        toastNoTextToCopy: "ไม่มีข้อความให้คัดลอก",
        toastCopied: "คัดลอกแล้ว",
        toastCopyFailed: "คัดลอกล้มเหลว",
        toastScoreReset: "รีเซ็ตคะแนนแล้ว",
        toastSaved: "บันทึกแล้ว",
        toastObsError: "เชื่อมต่อ OBS ไม่สำเร็จ",
    },
    // Korean
    ko: {
        appTitle: "축구 스코어보드 컨트롤러 - V2.2",
        excel: "엑셀",
        matchId: "ID:",
        load: "로드",
        teamA: "팀 A",
        teamB: "팀 B",
        editHint: "이름을 수정하거나 /로 새 줄을 추가하세요",
        ok: "확인",
        label1: "레이블 1",
        label2: "레이블 2",
        label3: "레이블 3",
        swap: "팀 교체",
        reset: "재설정",
        half: "전/후반",
        injuryTime: "추가 시간",
        countdown: "카운트다운",
        countdownHint: "카운트다운 타이머",
        settings: "설정",
        copy: "복사",
        help: "도움말",
        donate: "후원",
        version: "OBS Dock UI 스코어보드 - 버전 2.2",
        detailsTitle: "공지 텍스트 설정",
        detailsDesc: "아래 태그를 사용하여 데이터를 자동으로 가져오는 메시지를 만드세요.",
        tagsTitle: "사용 가능한 태그",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- 팀 A 이름' },
            { code: '&lt;TeamB&gt;', desc: '- 팀 B 이름' },
            { code: '&lt;score_team_a&gt;', desc: '- 팀 A 점수' },
            { code: '&lt;score_team_b&gt;', desc: '- 팀 B 점수' },
            { code: '&lt;time_counter&gt;', desc: '- 현재 시간 (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- 전/후반 (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- 레이블 1 텍스트' },
            { code: '&lt;label2&gt;', desc: '- 레이블 2 텍스트' },
            { code: '&lt;label3&gt;', desc: '- 레이블 3 텍스트' },
        ],
        save: "저장",
        close: "닫기",
        helpTitle: "사용 방법",
        helpStep1: "1. 모든 로고 파일을 <code>C:/OBSAssets/logos</code>에 넣으세요.",
        helpStep2: "2. <i class='fas fa-file-excel'></i> 엑셀 버튼을 클릭하여 데이터 파일을 선택하세요.",
        helpStep3: "3. 원하는 경기 ID를 선택하고 <i class='fas fa-check'></i> 로드를 클릭하세요.",
        sourcesTitle: "필요한 OBS 소스",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- 팀 A를 위한 **색상 소스**' },
            { code: 'Color_Team_B', desc: '- 팀 B를 위한 **색상 소스**' },
            { code: 'logo_team_a', desc: '- 팀 A 로고를 위한 **이미지 소스**' },
            { code: 'logo_team_b', desc: '- 팀 B 로고를 위한 **이미지 소스**' },
            { code: 'name_team_a', desc: '- 팀 A 이름을 위한 **텍스트 (GDI+)**' },
            { code: 'name_team_b', desc: '- 팀 B 이름을 위한 **텍스트 (GDI+)**' },
            { code: 'score_team_a', desc: '- 팀 A 점수를 위한 **텍스트 (GDI+)**' },
            { code: 'score_team_b', desc: '- 팀 B 점수를 위한 **텍스트 (GDI+)**' },
            { code: 'label_1/2/3', desc: '- 레이블을 위한 텍스트 (GDI+)' },
            { code: 'half_text', desc: '- 전/후반을 위한 텍스트 (GDI+)' },
            { code: 'time_counter', desc: '- 타이머를 위한 텍스트 (GDI+)' },
            { code: 'injury_time_text', desc: '- 추가 시간을 위한 **텍스트 (GDI+)** (+1)' },
        ],
        understand: "이해했습니다",
        donateTitle: "후원하기",
        donateThai: "태국인을 위해 (스코어보드용)",
        donateForeign: "외국인용 (태국 외)",
        toastLoadFileFirst: "먼저 파일을 업로드하세요",
        toastMatchNotFound: "경기 ID를 찾을 수 없습니다:",
        toastLoaded: "ID 로드 성공:",
        toastSuccess: "성공",
        toastSwapped: "팀이 교체되었습니다",
        toastNoTextToCopy: "복사할 텍스트가 없습니다",
        toastCopied: "클립보드에 복사됨",
        toastCopyFailed: "복사 실패",
        toastScoreReset: "점수 재설정됨",
        toastSaved: "저장됨",
        toastObsError: "OBS 연결 실패",
    },
    // Lao
    lo: {
        appTitle: "ໂຕຄວບຄຸມກະດານຄະແນນບານເຕະ - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "ໂຫຼດ",
        teamA: "ທີມ A",
        teamB: "ທີມ B",
        editHint: "ແກ້ໄຂຊື່ ຫຼື ເພີ່ມແຖວໃໝ່ດ້ວຍ /",
        ok: "ຕົກລົງ",
        label1: "ປ້າຍ 1",
        label2: "ປ້າຍ 2",
        label3: "ປ້າຍ 3",
        swap: "ສลับຝັ່ງ",
        reset: "ຣີເຊັດ",
        half: "ເຄິ່ງ",
        injuryTime: "ທົດເວລາ",
        countdown: "ນັບຖອຍຫຼັງ",
        countdownHint: "ໂຕນັບເວລາຖອຍຫຼັງ",
        settings: "ຕັ້ງຄ່າ",
        copy: "ສຳເນົາ",
        help: "ວິທີໃຊ້",
        donate: "ສະໜັບສະໜູນ",
        version: "OBS Dock UI Scoreboard - ເວີຊັ່ນ 2.2",
        detailsTitle: "ຕັ້ງຄ່າຂໍ້ຄວາມປະກາດ",
        detailsDesc: "ສ້າງຂໍ້ຄວາມໂດຍໃຊ້ແທັກຂ້າງລຸ່ມເພື່ອດຶງຂໍ້ມູນອັດຕະໂນມັດ.",
        tagsTitle: "ແທັກທີ່ໃຊ້ໄດ້",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ຊື່ທີມ A' },
            { code: '&lt;TeamB&gt;', desc: '- ຊື່ທີມ B' },
            { code: '&lt;score_team_a&gt;', desc: '- ຄະແນນທີມ A' },
            { code: '&lt;score_team_b&gt;', desc: '- ຄະແນນທີມ B' },
            { code: '&lt;time_counter&gt;', desc: '- ເວລາປັດຈຸບັນ (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- ເຄິ່ງເວລາ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 1' },
            { code: '&lt;label2&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 2' },
            { code: '&lt;label3&gt;', desc: '- ຂໍ້ຄວາມປ້າຍ 3' },
        ],
        save: "ບັນທຶກ",
        close: "ປິດ",
        helpTitle: "ວິທີການໃຊ້ງານ",
        helpStep1: "1. ເອົາໄຟລ໌ໂລໂກ້ທັງໝົດໄປໄວ້ທີ່ <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. ກົດປຸ່ມ <i class='fas fa-file-excel'></i> Excel ເພື່ອເລືອກໄຟລ໌ຂໍ້ມູນ.",
        helpStep3: "3. ເລືອກ Match ID ທີ່ຕ້ອງການ ແລ້ວກົດ <i class='fas fa-check'></i> ໂຫຼດ.",
        sourcesTitle: "OBS Sources ທີ່ຕ້ອງມີ",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** ສຳລັບສີທີມ A' },
            { code: 'Color_Team_B', desc: '- **Color Source** ສຳລັບສີທີມ B' },
            { code: 'logo_team_a', desc: '- **Image Source** ສຳລັບໂລໂກ້ທີມ A' },
            { code: 'logo_team_b', desc: '- **Image Source** ສຳລັບໂລໂກ້ທີມ B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** ສຳລັບຊື່ທີມ A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** ສຳລັບຊື່ທີມ B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** ສຳລັບຄະແນນທີມ A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** ສຳລັບຄະແນນທີມ B' },
            { code: 'label_1/2/3', desc: '- Text (GDI+) ສຳລັບປ້າຍຕ່າງໆ' },
            { code: 'half_text', desc: '- Text (GDI+) ສຳລັບເຄິ່ງເວລາ' },
            { code: 'time_counter', desc: '- Text (GDI+) ສຳລັບໂຕນັບເວລາ' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** ສຳລັບທົດເວລາບາດເຈັບ (+1)' },
        ],
        understand: "ເຂົ້າໃຈແລ້ວ",
        donateTitle: "ຮ່ວມສະໜັບສະໜູນ",
        donateThai: "ສຳລັບຄົນໄທ (ຂຶ້ນ Scoreboard)",
        donateForeign: "ສຳລັບຕ່າງປະເທດ",
        toastLoadFileFirst: "ກະລຸນາອັບໂຫຼດໄຟລ໌ກ່ອນ",
        toastMatchNotFound: "ບໍ່ພົບ Match ID:",
        toastLoaded: "ໂຫຼດ ID ສຳເລັດ:",
        toastSuccess: "ສຳເລັດ",
        toastSwapped: "ສลับຝັ່ງທີມແລ້ວ",
        toastNoTextToCopy: "ບໍ່ມີຂໍ້ຄວາມໃຫ້ສຳເນົາ",
        toastCopied: "ສຳເນົາແລ້ວ",
        toastCopyFailed: "ສຳເນົາລົ້ມເຫຼວ",
        toastScoreReset: "ຣີເຊັດຄະແນນແລ້ວ",
        toastSaved: "ບັນທຶກແລ້ວ",
        toastObsError: "ເຊື່ອມຕໍ່ OBS ບໍ່ສຳເລັດ",
    },
    // Khmer (Cambodian)
    km: {
        appTitle: "កម្មវិធីបញ្ជាតារាងពិន្ទុបាល់ទាត់ - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "ផ្ទុក",
        teamA: "ក្រុម A",
        teamB: "ក្រុម B",
        editHint: "កែឈ្មោះ ឬបន្ថែមបន្ទាត់ថ្មីជាមួយ /",
        ok: "យល់ព្រម",
        label1: "ស្លាក ១",
        label2: "ស្លាក ២",
        label3: "ស្លាក ៣",
        swap: "ប្តូរក្រុម",
        reset: "កំណត់ឡើងវិញ",
        half: "តង់",
        injuryTime: "ម៉ោងបន្ថែម",
        countdown: "រាប់ថយក្រោយ",
        countdownHint: "កម្មវិធីកំណត់เวลារាប់ថอยหลัง",
        settings: "ការកំណត់",
        copy: "ចម្លង",
        help: "ជំនួយ",
        donate: "គាំទ្រ",
        version: "OBS Dock UI Scoreboard - កំណែ 2.2",
        detailsTitle: "ការកំណត់អត្ថបទប្រកាស",
        detailsDesc: "បង្កើតសារដោយប្រើស្លាកខាងក្រោមដើម្បីទាញទិន្នន័យដោយស្វ័យប្រវត្តិ។",
        tagsTitle: "ស្លាកដែលមាន",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- ឈ្មោះក្រុម A' },
            { code: '&lt;TeamB&gt;', desc: '- ឈ្មោះក្រុម B' },
            { code: '&lt;score_team_a&gt;', desc: '- ពិន្ទុក្រុម A' },
            { code: '&lt;score_team_b&gt;', desc: '- ពិន្ទុក្រុម B' },
            { code: '&lt;time_counter&gt;', desc: '- ពេលវេលាបច្ចុប្បន្ន (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- តង់ (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- អត្ថបទស្លាក ១' },
            { code: '&lt;label2&gt;', desc: '- អត្ថបទស្លាក ២' },
            { code: '&lt;label3&gt;', desc: '- អត្ថបទស្លាក ៣' },
        ],
        save: "រក្សាទុក",
        close: "បិទ",
        helpTitle: "របៀបប្រើ",
        helpStep1: "1. ដាក់ឯកសារនិមិត្តសញ្ញាទាំងអស់ក្នុង <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. ចុចប៊ូតុង <i class='fas fa-file-excel'></i> Excel ដើម្បីជ្រើសរើសឯកសារទិន្នន័យ។",
        helpStep3: "3. ជ្រើសរើស Match ID ដែលចង់បាន ហើយចុច <i class='fas fa-check'></i> ផ្ទុក។",
        sourcesTitle: "OBS Sources ដែលត្រូវការ",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Color Source** សម្រាប់ក្រុម A' },
            { code: 'Color_Team_B', desc: '- **Color Source** សម្រាប់ក្រុម B' },
            { code: 'logo_team_a', desc: '- **Image Source** សម្រាប់និមិត្តសញ្ញាក្រុម A' },
            { code: 'logo_team_b', desc: '- **Image Source** សម្រាប់និមិត្តសញ្ញាក្រុម B' },
            { code: 'name_team_a', desc: '- **Text (GDI+)** សម្រាប់ឈ្មោះក្រុម A' },
            { code: 'name_team_b', desc: '- **Text (GDI+)** សម្រាប់ឈ្មោះក្រុម B' },
            { code: 'score_team_a', desc: '- **Text (GDI+)** សម្រាប់ពិន្ទុក្រុម A' },
            { code: 'score_team_b', desc: '- **Text (GDI+)** សម្រាប់ពិន្ទុក្រុម B' },
            { code: 'label_1/2/3', desc: '- Text (GDI+) សម្រាប់ស្លាក' },
            { code: 'half_text', desc: '- Text (GDI+) សម្រាប់តង់' },
            { code: 'time_counter', desc: '- Text (GDI+) សម្រាប់កម្មវិធីកំណត់เวลา' },
            { code: 'injury_time_text', desc: '- **Text (GDI+)** សម្រាប់ម៉ោងបន្ថែម (+1)' },
        ],
        understand: "យល់ហើយ",
        donateTitle: "គាំទ្រពួកយើង",
        donateThai: "សម្រាប់ជនជាតិថៃ (សម្រាប់តារាងពិន្ទុ)",
        donateForeign: "សម្រាប់ជនបរទេស (ក្រៅប្រទេសថៃ)",
        toastLoadFileFirst: "សូមអាប់ឡូតឯកសារជាមុនសិន",
        toastMatchNotFound: "រកមិនឃើញ Match ID:",
        toastLoaded: "បានផ្ទុក ID:",
        toastSuccess: "ជោគជ័យ",
        toastSwapped: "បានប្តូរក្រុម",
        toastNoTextToCopy: "គ្មានអត្ថបទសម្រាប់ចម្លង",
        toastCopied: "បានចម្លងទៅក្ដារតម្បៀតខ្ទាស់",
        toastCopyFailed: "ការចម្លងបានបរាជ័យ",
        toastScoreReset: "បានកំណត់ពិន្ទុឡើងវិញ",
        toastSaved: "បានរក្សាទុក",
        toastObsError: "ការភ្ជាប់ទៅ OBS បានបរាជ័យ",
    },
    // Brazilian Portuguese
    'pt-br': {
        appTitle: "Controlador de Placar de Futebol - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "Carregar",
        teamA: "Equipe A",
        teamB: "Equipe B",
        editHint: "Edite o nome ou adicione uma nova linha com /",
        ok: "OK",
        label1: "Rótulo 1",
        label2: "Rótulo 2",
        label3: "Rótulo 3",
        swap: "Trocar Lados",
        reset: "Resetar",
        half: "Tempo",
        injuryTime: "Acréscimos",
        countdown: "Contagem",
        countdownHint: "Temporizador de contagem regressiva",
        settings: "Config.",
        copy: "Copiar",
        help: "Ajuda",
        donate: "Apoiar",
        version: "OBS Dock UI Scoreboard - Versão 2.2",
        detailsTitle: "Configurações de Texto de Anúncio",
        detailsDesc: "Crie mensagens usando as tags abaixo para puxar dados automaticamente.",
        tagsTitle: "Tags Disponíveis",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Nome da Equipe A' },
            { code: '&lt;TeamB&gt;', desc: '- Nome da Equipe B' },
            { code: '&lt;score_team_a&gt;', desc: '- Placar da Equipe A' },
            { code: '&lt;score_team_b&gt;', desc: '- Placar da Equipe B' },
            { code: '&lt;time_counter&gt;', desc: '- Tempo Atual (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Tempo (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Texto do Rótulo 1' },
            { code: '&lt;label2&gt;', desc: '- Texto do Rótulo 2' },
            { code: '&lt;label3&gt;', desc: '- Texto do Rótulo 3' },
        ],
        save: "Salvar",
        close: "Fechar",
        helpTitle: "Como Usar",
        helpStep1: "1. Coloque todos os arquivos de logo em <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. Clique no botão <i class='fas fa-file-excel'></i> Excel para selecionar o arquivo de dados.",
        helpStep3: "3. Selecione o ID da Partida desejado e clique em <i class='fas fa-check'></i> Carregar.",
        sourcesTitle: "Fontes OBS Necessárias",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Fonte de Cor** para Equipe A' },
            { code: 'Color_Team_B', desc: '- **Fonte de Cor** para Equipe B' },
            { code: 'logo_team_a', desc: '- **Fonte de Imagem** para Logo da Equipe A' },
            { code: 'logo_team_b', desc: '- **Fonte de Imagem** para Logo da Equipe B' },
            { code: 'name_team_a', desc: '- **Texto (GDI+)** para Nome da Equipe A' },
            { code: 'name_team_b', desc: '- **Texto (GDI+)** para Nome da Equipe B' },
            { code: 'score_team_a', desc: '- **Texto (GDI+)** para Placar da Equipe A' },
            { code: 'score_team_b', desc: '- **Texto (GDI+)** para Placar da Equipe B' },
            { code: 'label_1/2/3', desc: '- Texto (GDI+) para Rótulos' },
            { code: 'half_text', desc: '- Texto (GDI+) para Tempo' },
            { code: 'time_counter', desc: '- Texto (GDI+) para Temporizador' },
            { code: 'injury_time_text', desc: '- **Texto (GDI+)** para Acréscimos (+1)' },
        ],
        understand: "Entendi",
        donateTitle: "Apoie-nos",
        donateThai: "Para Tailandeses (para o Placar)",
        donateForeign: "Para Estrangeiros (Fora da Tailândia)",
        toastLoadFileFirst: "Por favor, carregue um arquivo primeiro",
        toastMatchNotFound: "ID da Partida não encontrado:",
        toastLoaded: "ID carregado:",
        toastSuccess: "Sucesso",
        toastSwapped: "Equipes trocadas",
        toastNoTextToCopy: "Nenhum texto para copiar",
        toastCopied: "Copiado para a área de transferência",
        toastCopyFailed: "Falha ao copiar",
        toastScoreReset: "Placar resetado",
        toastSaved: "Salvo",
        toastObsError: "Falha ao conectar ao OBS",
    },
    // Spanish
    es: {
        appTitle: "Controlador de Marcador de Fútbol - V2.2",
        excel: "Excel",
        matchId: "ID:",
        load: "Cargar",
        teamA: "Equipo A",
        teamB: "Equipo B",
        editHint: "Editar nombre o añadir línea con /",
        ok: "OK",
        label1: "Etiqueta 1",
        label2: "Etiqueta 2",
        label3: "Etiqueta 3",
        swap: "Cambiar Equipos",
        reset: "Reiniciar",
        half: "Periodo",
        injuryTime: "Tiempo añadido",
        countdown: "Regresiva",
        countdownHint: "Temporizador de cuenta regresiva",
        settings: "Ajustes",
        copy: "Copiar",
        help: "Ayuda",
        donate: "Donar",
        version: "OBS Dock UI Scoreboard - Versión 2.2",
        detailsTitle: "Configuración de Texto de Anuncio",
        detailsDesc: "Crea un mensaje usando las etiquetas de abajo para obtener datos automáticamente.",
        tagsTitle: "Etiquetas Disponibles",
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: '- Nombre Equipo A' },
            { code: '&lt;TeamB&gt;', desc: '- Nombre Equipo B' },
            { code: '&lt;score_team_a&gt;', desc: '- Marcador Equipo A' },
            { code: '&lt;score_team_b&gt;', desc: '- Marcador Equipo B' },
            { code: '&lt;time_counter&gt;', desc: '- Tiempo Actual (MM:SS)' },
            { code: '&lt;half_text&gt;', desc: '- Periodo (1st/2nd)' },
            { code: '&lt;label1&gt;', desc: '- Texto Etiqueta 1' },
            { code: '&lt;label2&gt;', desc: '- Texto Etiqueta 2' },
            { code: '&lt;label3&gt;', desc: '- Texto Etiqueta 3' },
        ],
        save: "Guardar",
        close: "Cerrar",
        helpTitle: "Cómo Usar",
        helpStep1: "1. Coloca todos los logos en <code>C:/OBSAssets/logos</code>",
        helpStep2: "2. Haz clic en el botón <i class='fas fa-file-excel'></i> Excel para seleccionar el archivo de datos.",
        helpStep3: "3. Selecciona el ID del partido y haz clic en <i class='fas fa-check'></i> Cargar.",
        sourcesTitle: "Fuentes de OBS Requeridas",
        sourcesList: [
            { code: 'Color_Team_A', desc: '- **Fuente de Color** para Equipo A' },
            { code: 'Color_Team_B', desc: '- **Fuente de Color** para Equipo B' },
            { code: 'logo_team_a', desc: '- **Fuente de Imagen** para Logo Equipo A' },
            { code: 'logo_team_b', desc: '- **Fuente de Imagen** para Logo Equipo B' },
            { code: 'name_team_a', desc: '- **Texto (GDI+)** para Nombre Equipo A' },
            { code: 'name_team_b', desc: '- **Texto (GDI+)** para Nombre Equipo B' },
            { code: 'score_team_a', desc: '- **Texto (GDI+)** para Marcador Equipo A' },
            { code: 'score_team_b', desc: '- **Texto (GDI+)** para Marcador Equipo B' },
            { code: 'label_1/2/3', desc: '- Texto (GDI+) para Etiquetas' },
            { code: 'half_text', desc: '- Texto (GDI+) para Periodo' },
            { code: 'time_counter', desc: '- Texto (GDI+) para Temporizador' },
            { code: 'injury_time_text', desc: '- **Texto (GDI+)** para Tiempo añadido (+1)' },
        ],
        understand: "Entendido",
        donateTitle: "Apóyanos",
        donateThai: "Para usuarios de Tailandia",
        donateForeign: "Para usuarios internacionales",
        toastLoadFileFirst: "Por favor, carga un archivo primero",
        toastMatchNotFound: "ID de partido no encontrado:",
        toastLoaded: "ID cargado:",
        toastSuccess: "Éxito",
        toastSwapped: "Equipos cambiados",
        toastNoTextToCopy: "No hay texto para copiar",
        toastCopied: "Copiado al portapapeles",
        toastCopyFailed: "Error al copiar",
        toastScoreReset: "Marcador reiniciado",
        toastSaved: "Guardado",
        toastObsError: "Fallo al conectar con OBS",
    }
};