// fcp_v2_assets/languages.js
// ไฟล์สำหรับเก็บคำแปลทั้งหมด

export const translations = {
    // English
    en: {
        appTitle: "Football Scoreboard Controller - V2.9.2 (OBSScore)",
        excel: "Excel",
        matchId: "ID:",
        load: "Load",
        teamA: "Team A",
        teamB: "Team B",
        edit: "Edit",
        editHint: "Edit name or add new line with /",
        ok: "OK",
        label1: "Label 1",
        label2: "Label 2",
        label3: "Label 3",
        label4: "Label 4",
        label5: "Label 5",
        label6: "Label 6",
        swap: "Swap Teams",
        reset: "Reset",
        fullReset: "Reset",
        score2Label: "Fouls/Counts",
        hide: "Hide",
        show: "Show",
        score2VisibilityGroup: "Score 2 Visibility Control",
        swapCardVisibility: "Swap Card Visibility",
        actionCardVisibility: "Action Buttons Visibility",
        labelCount: "Label Count:",
        visibilityTitle: "Card Visibility Control",
        resetKeybinds: "Reset Keybinds",
        resetColors: "Clear Team Color Memory",
        half: "Half",
        injuryTime: "Added Time",
        countdown: "Down",
        countdownHint: "Countdown Timer",
        resetToZeroHint: "Reset timer to 00:00",
        resetToStartHint: "Reset timer to configured start time",
        settings: "Settings",
        copy: "Message",
        help: "Help",
        donate: "Donate",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "Update Version 2.9.2",
        detailsTitle: "Settings & Announcement",
        detailsDesc: "Customize general settings and announcement text below.",
        tagsTitle: "Available Tags for Announcement",
        keybindsTitle: "Keyboard Shortcuts",
        keybindsListLabel: "Item",
        clear: "Clear",
        // START: CHANGED FOR SOURCE CONTROL
        actionSettingsTitle: "Action Button Settings (Source Visibility)",
        actionSettingsDesc: "Set button names, colors, height, and the Target OBS Source/Action to control visibility directly. The Source/Group must be in the active Scene.",
        actionSettingsName: "Name",
        actionSettingsColor: "Color",
        actionSettingsHeight: "Height (px)",
        actionSettingsSource: "Source/Group Name",
        actionSettingsAction: "Action",
        actionSettingsEditSave: "Edit/Save",
        // END: CHANGED FOR SOURCE CONTROL
        keybindsList: [
            { id: "scoreA_plus", label: "+ Score A (Main)", default: "" },
            { id: "scoreA_minus", label: "- Score A (Main)", default: "" },
            { id: "scoreB_plus", label: "+ Score B (Main)", default: "" },
            { id: "scoreB_minus", label: "- Score B (Main)", default: "" },
            { id: "score2A_plus", label: "+ Score A (Sub)", default: "" },
            { id: "score2A_minus", label: "- Score A (Sub)", default: "" },
            { id: "score2B_plus", label: "+ Score B (Sub)", default: "" },
            { id: "score2B_minus", label: "- Score B (Sub)", default: "" },
            { id: "timer_playpause", label: "Play/Pause Timer", default: "" },
            { id: "timer_resetstart", label: "Reset to Start Time", default: "" },
            { id: "timer_togglehalf", label: "Toggle Half", default: "" },
            { id: "full_reset", label: "Full Reset (All)", default: "" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: 'Team A Name' },
            { code: '&lt;TeamB&gt;', desc: 'Team B Name' },
            { code: '&lt;score_team_a&gt;', desc: 'Team A Score' },
            { code: '&lt;score_team_b&gt;', desc: 'Team B Score' },
            { code: '&lt;score2_team_a&gt;', desc: 'Team A Score 2 (Fouls/Counts)' },
            { code: '&lt;score2_team_b&gt;', desc: 'Team B Score 2 (Fouls/Counts)' },
            { code: '&lt;time_counter&gt;', desc: 'Current Time (MM:SS)' },
            { code: '&lt;label1&gt;', desc: 'Label 1 Text' },
            { code: '&lt;label2&gt;', desc: 'Label 2 Text' },
            { code: '&lt;label3&gt;', desc: 'Label 3 Text' },
            { code: '&lt;label4&gt;', desc: 'Label 4 Text' },
            { code: '&lt;label5&gt;', desc: 'Label 5 Text' },
        ],
        save: "Save",
        // V2.9.2 Settings Tabs
        settingsTabGeneral: "📝 Announce",
        settingsTabActions: "🎮 Actions",
        settingsTabKeybinds: "⌨️ Keys",
        settingsTabVisibility: "👁️ Display",
        settingsTabData: "📊 Data",
        // V2.9.2 Confirm Dialog
        confirmResetTitle: "Confirm Full Reset",
        confirmResetMsg: "This will reset all scores, timer, half, and injury time. Are you sure?",
        confirmYes: "Yes, Reset All",
        confirmNo: "Cancel",
        // V2.9.2 Color Count
        colorCount: "Team Colors:",
        colorCount1: "1 Color",
        colorCount2: "2 Colors",
        // V2.9.2 Timer State
        timerRunning: "Running",
        timerPaused: "Paused",
        // V2.9.2 OBS Source Creation
        createObsSources: "Auto-Create Sources in OBS",
        createObsSourcesDesc: "Create all required text & color sources in the current OBS scene automatically.",
        toastSourcesCreated: "All OBS sources created successfully!",
        toastSourcesPartial: "Some sources already exist, others created.",
        toastSourcesFailed: "Failed to create sources. Check OBS connection.",
        // V2.9.2 Help
        helpStep4: "4. Use the <i class='fas fa-cog'></i> Settings button to configure action buttons, keyboard shortcuts, display settings, and data sources.",
        helpStep5: "5. Use the <i class='fas fa-mobile-alt'></i> Mobile button to control from a smartphone.",
        helpStep6: "6. Click <strong>'Auto-Create Sources in OBS'</strong> below to generate all required sources automatically.",
        // V2.9.2 Donate
        donateShopee: "Shopee (Affiliate)",
        donateDesc: "This program is free! Thank you for supporting the developer.",
        donateShopeeDesc: "Support by shopping on Shopee via this affiliate link.",
        donateEasyDonateDesc: "Alternative: Support via EasyDonate.",
        donateSponsorTitle: "Support the Developer",
        donateClose: "Close",
        // V2.9.2 Visibility extras (translated labels)
        visExtraTimeBtns: "Extra Time Buttons",
        visResetToStart: "Reset to Start",
        visSetTimeBtn: "Set Time Button",
        visCountdown: "Countdown",
        visControlTitle: "Timer Controls Visibility",
        maxHalvesLabel: "Max Halves:",
        close: "Close",
        saveAndUpdate: "Save & Update",
        helpTitle: "How to Use",
        helpWebSocket: "<strong>Prerequisite:</strong> Enable <strong>OBS WebSocket</strong> in OBS Studio (Tools > WebSocket Server Settings). <br>Set Port: <code>4455</code> | <strong>Uncheck 'Enable Authentication'</strong>.",
        helpStep1: "1. Click the <i class='fas fa-folder-open'></i> icon to set your logo folder path. The default is <code>C:/OBSAssets/logos</code>. **You need to click the Edit button inside the popup to change and save the path.**",
        helpStep2: "2. Click <i class='fas fa-file-excel'></i> Excel button to select your data file (or use Google Sheets).",
        helpStep3: "3. Select the desired Match ID and click <i class='fas fa-check'></i> Load.",
        sourcesTitle: "Required OBS Sources (Click to Copy)",
        sourcesTableHeaders: ["Source Name", "Source Type", "Details"],
        selectMatchId: "Select Match ID",
        loadBtn: "LOAD",
        // V2.9.2 Welcome Sponsor
        donateFreeMsg: "This program is free! Thank you for your support.",
        donateShopeeMsg: "You can support me by shopping on Shopee via this Affiliate link.",
        donateShopeeAlt: "QR Code for Jamornz's Shopee",
        donateAltTitle: "Alternative Support Options",
        donateEasyDonateMsg: "Support via EasyDonate",
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'Team A (Primary Color)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'Team B (Primary Color)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'Team A (Secondary Color)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'Team B (Secondary Color)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'Team A Logo' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'Team B Logo' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'Team A Name' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'Team B Name' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'Team A Score (Main)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'Team B Score (Main)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'Team A Score 2 (Fouls/Counts)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'Team B Score 2 (Fouls/Counts)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'Label 1 Text' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'Label 2 Text' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'Label 3 Text' },
            { code: 'label_4', type: 'Text (GDI+)', desc: 'Label 4 Text' },
            { code: 'label_5', type: 'Text (GDI+)', desc: 'Label 5 Text' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'Half (1st/2nd)' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'Timer' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'Added Time (+1)' },
        ],
        understand: "Got it",
        donateTitle: "Support Us",
        donateThai: "For Thais (for Scoreboard)",
        donateForeign: "For Foreigners (Outside Thailand)",
        timeSettingsTitle: "Set Start Time",
        timeSettingsMinutes: "Minutes",
        timeSettingsSeconds: "Seconds",
        logoPathTitle: "Logo Folder Path & Cache",
        logoPathDesc: "The current OBS Logo Folder Path is:",
        logoPathHint: "Set logo folder path",
        changelogTitle: "Update History",
        changelogContent: `
            <ul class="changelog-list">
                <li>
                    <h5>Version 2.9.2</h5>
                    <ul>
                        <li>**Settings:** Reorganized into Tabs (Announce, Actions, Keys, Display, Data) for easier access.</li>
                        <li>**UI:** Bigger color pickers, 1 or 2 color display option, timer running/paused indicator.</li>
                        <li>**UX:** Confirm dialog before full reset, Enter/Escape key for team name editing, tooltips.</li>
                        <li>**OBS:** Auto-create all required sources in current scene via WebSocket.</li>
                        <li>**Fix:** Popup blur in OBS Dock, CSS syntax errors, viewport meta, toast positioning.</li>
                        <li>**Donate:** Cleaner sponsor/donate popup layout.</li>
                    </ul>
                </li>
                <li>
                    <h5>Version 2.9</h5>
                    <ul>
                        <li>Online User Count, Responsive Design, Visibility Controls, Logo Cache, Google Sheets.</li>
                    </ul>
                </li>
            </ul> `,
        toastLoadFileFirst: "Please upload a file first",
        toastMatchNotFound: "Match ID not found:",
        toastLoaded: "Loaded ID:",
        toastSuccess: "Success",
        toastSwapped: "Teams swapped",
        toastNoTextToCopy: "No text to copy",
        toastCopied: "Copied to clipboard",
        toastCopyFailed: "Copy failed",
        toastScoreReset: "Score reset",
        toastScore2Reset: "Score 2 reset",
        toastFullReset: "Scoreboard fully reset",
        toastCopiedSourceName: "Copied source name:",
        toastSaved: "Saved",
        toastKeybindsSaved: "Keybind saved!",
        toastActionSaved: "Action button settings saved! (Source Control)",
        toastColorsCleared: "Team color memory cleared!",
        toastObsError: "Failed to connect to OBS",
        toastActionControlFailed: "Failed to control source:",
        toastInvalidTime: "Invalid time format. Please check minutes and seconds (0-59).",
        toastTimeSet: "Start time has been set and updated.",
        logoCacheTitle: "Logo Cache (Dock UI Display)",
        logoCacheDesc: "Drop image files here (PNG/JPG) to enable them to display on the Dock UI without OBS file restrictions. File name (without extension) is the Logo Key.",
        logoDropZoneText: "Drag and Drop Logo Files here",
        logoCacheListTitle: "Cached Logos:",
        logoCacheEmpty: "No logos are currently cached.",
        logoCacheSaved: "Logo cached:",
        toastCacheSaveFailed: "Failed to save logo to cache!",
        clearCache: "Clear Logo Cache",
        toastCacheCleared: "Logo Cache cleared!",
        logoCacheSummary: "Import Summary:",
        logoCacheSuccess: "Success:",
        logoCacheFailed: "Failed:",
        logoCacheTotal: "Total Cached:",

        // NEW STRINGS FOR V2.9
        mobileControlTitle: "Mobile Remote Control (OBSScore)",
        mobileControlDesc: "Control your scoreboard from anywhere via smartphone.",
        createRoom: "Create Room",
        roomName: "Room Name",
        roomId: "Room ID",
        scanQr: "Scan QR to Connect",
        waitingConnection: "Waiting for connection...",
        connectedDevice: "Connected Device:",
        disconnect: "Disconnect",
        openMobileApp: "Open Mobile Web App",
        remoteStatus: "Status:",
        remoteStatusWait: "Standby",
        remoteStatusReady: "Ready to pair",
        remoteStatusConnected: "Connected",
        dataSourceTitle: "Data Source Configuration",
        dsExcel: "Excel File (Offline)",
        dsGoogleSheet: "Google Sheet (Online)",
        confirm: "Confirm",
        toastGoogleSheetSuccess: "Google Sheet Loaded Successfully!",
        toastGoogleSheetError: "Failed to load Google Sheet. Check URL or permission.",
        loadFromGoogleSheet: "Fetch / Reload GS",
        labelCount: "Label Count:",
        dsExcelGuide: "<strong>Excel Guide:</strong> Ensure your file uses these columns logic. You can copy the headers below. (Unwanted columns can be deleted)",
        dsColumnList: "MatchID, LogoA, TeamA, LogoB, TeamB, label1, label2, label3, label4, label5",
        dsCopyColumns: "Copy Columns",
        dsGoogleSheetGuide: "<strong>Google Sheets Guide:</strong><br>1. Click <strong>Share</strong> > General Access > <strong>Anyone with the link</strong>.<br>2. Click <strong>Copy link</strong>.<br>3. Paste the link below.<br>4. Go back to main screen > Click <strong>Load/Fetch</strong> > Select Match ID.",
    },
    // ภาษาไทย
    th: {
        appTitle: "โปรแกรมควบคุมสกอร์บอร์ดฟุตบอล - V2.9.2 (OBSScore)",
        excel: "Excel",
        matchId: "ID:",
        load: "โหลด",
        teamA: "ทีม A",
        teamB: "ทีม B",
        edit: "แก้ไข",
        editHint: "แก้ไขชื่อ หรือขึ้นบรรทัดใหม่ด้วยการใส่ /",
        ok: "ตกลง",
        label1: "ป้าย 1",
        label2: "ป้าย 2",
        label3: "ป้าย 3",
        label4: "ป้าย 4",
        label5: "ป้าย 5",
        swap: "สลับฝั่ง",
        reset: "รีเซ็ต",
        fullReset: "รีเซ็ต",
        score2Label: "ฟาวล์/แต้ม 2",
        hide: "ซ่อน",
        show: "แสดง",
        score2VisibilityGroup: "ควบคุมการแสดงผลคะแนน 2",
        swapCardVisibility: "ควบคุมการแสดงผล Card สลับฝั่ง",
        actionCardVisibility: "ควบคุมการแสดงผล Action Buttons",
        visibilityTitle: "ควบคุมการแสดงผล Card",
        resetKeybinds: "รีเซ็ตคีย์ลัด",
        resetColors: "ล้างหน่วยความจำสีทีม",
        half: "ครึ่ง",
        injuryTime: "ทดเวลา",
        countdown: "นับถอยหลัง",
        countdownHint: "ตัวนับเวลาถอยหลัง",
        resetToZeroHint: "รีเซ็ตเวลาเป็น 00:00",
        resetToStartHint: "รีเซ็ตตามเวลาที่ตั้งค่า",
        settings: "ตั้งค่า",
        copy: "ข้อความ",
        help: "วิธีใช้",
        donate: "สนับสนุน",
        footerAppName: "OBS Dock UI Scoreboard",
        changelog: "อัปเดตเวอร์ชัน 2.9.2",
        detailsTitle: "ตั้งค่า & ข้อความประกาศ",
        detailsDesc: "ตั้งค่าทั่วไปและข้อความประกาศด้านล่าง",
        tagsTitle: "Tags ที่ใช้งานได้สำหรับข้อความประกาศ",
        keybindsTitle: "ตั้งค่าคีย์ลัด (Keyboard Shortcuts)",
        keybindsListLabel: "รายการ",
        clear: "ล้างค่า",
        // START: CHANGED FOR SOURCE CONTROL
        actionSettingsTitle: "ตั้งค่า Action Button (ควบคุม Source Visibility)",
        actionSettingsDesc: "ตั้งค่าชื่อปุ่ม, สี, ความสูง และชื่อ Source/Group/Action ที่ต้องการควบคุมการแสดงผลโดยตรง โปรแกรมจะใช้ Scene ที่กำลัง Live อยู่ปัจจุบัน",
        actionSettingsName: "ชื่อปุ่ม",
        actionSettingsColor: "สี",
        actionSettingsHeight: "ความสูง (px)",
        actionSettingsSource: "ชื่อ Source/Group",
        actionSettingsAction: "Action",
        actionSettingsEditSave: "แก้ไข/บันทึก",
        // END: CHANGED FOR SOURCE CONTROL
        keybindsList: [
            { id: "scoreA_plus", label: "+ คะแนน A (หลัก)", default: "" },
            { id: "scoreA_minus", label: "- คะแนน A (หลัก)", default: "" },
            { id: "scoreB_plus", label: "+ คะแนน B (หลัก)", default: "" },
            { id: "scoreB_minus", label: "- คะแนน B (หลัก)", default: "" },
            { id: "score2A_plus", label: "+ คะแนน A (รอง)", default: "" },
            { id: "score2A_minus", label: "- คะแนน A (รอง)", default: "" },
            { id: "score2B_plus", label: "+ คะแนน B (รอง)", default: "" },
            { id: "score2B_minus", label: "- คะแนน B (รอง)", default: "" },
            { id: "timer_playpause", label: "เริ่ม/หยุด เวลา", default: "" },
            { id: "timer_resetstart", label: "รีเซ็ตไปเวลาเริ่มต้น", default: "" },
            { id: "timer_togglehalf", label: "สลับครึ่งเวลา", default: "" },
            { id: "full_reset", label: "รีเซ็ตทั้งหมด", default: "" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;', desc: 'ชื่อทีม A' },
            { code: '&lt;TeamB&gt;', desc: 'ชื่อทีม B' },
            { code: '&lt;score_team_a&gt;', desc: 'คะแนนทีม A' },
            { code: '&lt;score_team_b&gt;', desc: 'คะแนนทีม B' },
            { code: '&lt;score2_team_a&gt;', desc: 'คะแนน 2 ทีม A (ฟาวล์/แต้ม)' },
            { code: '&lt;score2_team_b&gt;', desc: 'คะแนน 2 ทีม B (ฟาวล์/แต้ม)' },
            { code: '&lt;time_counter&gt;', desc: 'เวลาปัจจุบัน (MM:SS)' },
            { code: '&lt;label1&gt;', desc: 'ข้อความ Label 1' },
            { code: '&lt;label2&gt;', desc: 'ข้อความ Label 2' },
            { code: '&lt;label3&gt;', desc: 'ข้อความ Label 3' },
            { code: '&lt;label4&gt;', desc: 'ข้อความ Label 4' },
            { code: '&lt;label5&gt;', desc: 'ข้อความ Label 5' },
        ],
        save: "บันทึก",
        // V2.9.2 Settings Tabs
        settingsTabGeneral: "📝 ประกาศ",
        settingsTabActions: "🎮 ปุ่ม",
        settingsTabKeybinds: "⌨️ คีย์ลัด",
        settingsTabVisibility: "👁️ แสดงผล",
        settingsTabData: "📊 ข้อมูล",
        // V2.9.2 Confirm Dialog
        confirmResetTitle: "ยืนยันการรีเซ็ตทั้งหมด",
        confirmResetMsg: "จะรีเซ็ตคะแนน, เวลา, ครึ่ง, ทดเวลา ทั้งหมด คุณแน่ใจหรือไม่?",
        confirmYes: "ใช่ รีเซ็ตทั้งหมด",
        confirmNo: "ยกเลิก",
        // V2.9.2 Color Count
        colorCount: "จำนวนสีทีม:",
        colorCount1: "1 สี",
        colorCount2: "2 สี",
        // V2.9.2 Timer State
        timerRunning: "กำลังเดิน",
        timerPaused: "หยุด",
        // V2.9.2 OBS Source Creation
        createObsSources: "สร้าง Source อัตโนมัติใน OBS",
        createObsSourcesDesc: "สร้าง Text & Color sources ที่จำเป็นทั้งหมดใน Scene ปัจจุบันของ OBS โดยอัตโนมัติ",
        toastSourcesCreated: "สร้าง OBS sources ทั้งหมดสำเร็จ!",
        toastSourcesPartial: "บาง source มีอยู่แล้ว สร้างที่เหลือสำเร็จ",
        toastSourcesFailed: "สร้าง sources ไม่สำเร็จ ตรวจสอบการเชื่อมต่อ OBS",
        // V2.9.2 Help
        helpStep4: "4. ใช้ปุ่ม <i class='fas fa-cog'></i> ตั้งค่า เพื่อปรับ action buttons, คีย์ลัด, การแสดงผล, และแหล่งข้อมูล",
        helpStep5: "5. ใช้ปุ่ม <i class='fas fa-mobile-alt'></i> มือถือ เพื่อควบคุมผ่านสมาร์ทโฟน",
        helpStep6: "6. คลิกปุ่ม <strong>'สร้าง Source อัตโนมัติ'</strong> ด้านล่างเพื่อสร้าง sources ทั้งหมดใน OBS อัตโนมัติ",
        // V2.9.2 Donate
        donateShopee: "Shopee (Affiliate)",
        donateDesc: "โปรแกรมนี้แจกฟรี! ขอขอบคุณทุกท่านที่สนับสนุน",
        donateShopeeDesc: "สนับสนุนผมด้วยการซื้อของใน Shopee ผ่านลิ้งค์ Affiliate นี้",
        donateEasyDonateDesc: "ทางเลือกอื่น: สนับสนุนผ่าน EasyDonate",
        donateSponsorTitle: "สนับสนุนผู้พัฒนา",
        donateClose: "ปิด",
        // V2.9.2 Visibility extras
        visExtraTimeBtns: "ปุ่มทดเวลา",
        visResetToStart: "รีเซ็ตไปเวลาเริ่มต้น",
        visSetTimeBtn: "ปุ่มตั้งเวลา",
        visCountdown: "นับถอยหลัง",
        visControlTitle: "แสดง/ซ่อนปุ่มเวลา",
        maxHalvesLabel: "จำนวนครึ่งเวลาสูงสุด:",
        close: "ปิด",
        saveAndUpdate: "บันทึกและอัปเดต",
        helpTitle: "วิธีการใช้งาน",
        helpWebSocket: "<strong>การเตรียมความพร้อม:</strong> เปิดใช้งาน <strong>OBS WebSocket</strong> ในโปรแกรม OBS (Tools > WebSocket Server Settings) <br>ตั้งค่า Port: <code>4455</code> | <strong>นำติ๊กถูกออกที่ 'Enable Authentication'</strong>",
        helpStep1: "1. กดปุ่ม <i class='fas fa-folder-open'></i> เพื่อตั้งค่าที่อยู่โฟลเดอร์โลโก้ (ค่าเริ่มต้นคือ <code>C:/OBSAssets/logos</code>) **คุณต้องกดปุ่ม แก้ไข ใน Popup เพื่อเปลี่ยนและบันทึกที่อยู่**",
        helpStep2: "2. กดปุ่ม <i class='fas fa-file-excel'></i> Excel หรือ Google Sheet เพื่อเลือกแหล่งข้อมูล",
        helpStep3: "3. เลือก Match ID ที่ต้องการ แล้วกด <i class='fas fa-check'></i> Load",
        sourcesTitle: "OBS Sources ที่ต้องมี (คลิกเพื่อคัดลอก)",
        selectMatchId: "เลือก Match ID",
        loadBtn: "โหลดข้อมูล",
        // V2.9.2 Welcome Sponsor
        donateFreeMsg: "โปรแกรมนี้แจกฟรี! ขอขอบคุณทุกท่านที่สนับสนุน",
        donateShopeeMsg: "คุณสามารถสนับสนุนผมด้วยการซื้อของใน Shopee ผ่านลิ้งค์ Affiliate นี้ได้",
        donateShopeeAlt: "QR Code สำหรับ Shopee ของ Jamornz",
        donateAltTitle: "ทางเลือกอื่นในการสนับสนุน",
        donateEasyDonateMsg: "สนับสนุนผ่าน EasyDonate",
        dsExcelGuide: "<strong>คำแนะนำ Excel:</strong> ตรวจสอบว่าไฟล์มีคอลัมน์ตามนี้ (สามารถคัดลอกไปวางได้ / คอลัมน์ที่ไม่ใช้ลบออกได้)",
        dsColumnList: "MatchID, LogoA, TeamA, LogoB, TeamB, label1, label2, label3, label4, label5",
        dsCopyColumns: "คัดลอกชื่อคอลัมน์",
        dsGoogleSheetGuide: "<strong>คำแนะนำ Google Sheets:</strong><br>1. กดปุ่ม <strong>แชร์ (Share)</strong> > การเข้าถึงทั่วไป > เลือก <strong>ทุกคนที่มีลิ้งค์ (Anyone with the link)</strong><br>2. กด <strong>คัดลอกลิ้งค์ (Copy link)</strong><br>3. นำลิ้งค์มาวางในช่องด้านล่าง<br>4. กลับไปหน้าหลัก > กดปุ่ม <strong>โหลดข้อมูล</strong> > เลือก Match ID",
        sourcesList: [
            { code: 'Color_Team_A', type: 'Color Source', desc: 'สีทีม A (สีหลัก)' },
            { code: 'Color_Team_B', type: 'Color Source', desc: 'สีทีม B (สีหลัก)' },
            { code: 'Color_Team_A_2', type: 'Color Source', desc: 'สีทีม A (สีรอง)' },
            { code: 'Color_Team_B_2', type: 'Color Source', desc: 'สีทีม B (สีรอง)' },
            { code: 'logo_team_a', type: 'Image Source', desc: 'โลโก้ทีม A' },
            { code: 'logo_team_b', type: 'Image Source', desc: 'โลโก้ทีม B' },
            { code: 'name_team_a', type: 'Text (GDI+)', desc: 'ชื่อทีม A' },
            { code: 'name_team_b', type: 'Text (GDI+)', desc: 'ชื่อทีม B' },
            { code: 'score_team_a', type: 'Text (GDI+)', desc: 'คะแนนทีม A (หลัก)' },
            { code: 'score_team_b', type: 'Text (GDI+)', desc: 'คะแนนทีม B (หลัก)' },
            { code: 'score2_team_a', type: 'Text (GDI+)', desc: 'คะแนน 2 ทีม A (ฟาวล์/แต้ม)' },
            { code: 'score2_team_b', type: 'Text (GDI+)', desc: 'คะแนน 2 ทีม B (ฟาวล์/แต้ม)' },
            { code: 'label_1', type: 'Text (GDI+)', desc: 'ข้อความ Label 1' },
            { code: 'label_2', type: 'Text (GDI+)', desc: 'ข้อความ Label 2' },
            { code: 'label_3', type: 'Text (GDI+)', desc: 'ข้อความ Label 3' },
            { code: 'label_4', type: 'Text (GDI+)', desc: 'ข้อความ Label 4' },
            { code: 'label_5', type: 'Text (GDI+)', desc: 'ข้อความ Label 5' },
            { code: 'half_text', type: 'Text (GDI+)', desc: 'ครึ่งเวลา' },
            { code: 'time_counter', type: 'Text (GDI+)', desc: 'ตัวนับเวลา' },
            { code: 'injury_time_text', type: 'Text (GDI+)', desc: 'ทดเวลาบาดเจ็บ (+1)' },
        ],
        understand: "เข้าใจแล้ว",
        donateTitle: "ร่วมสนับสนุน",
        donateThai: "สำหรับคนไทย (ขึ้น Scoreboard)",
        donateForeign: "สำหรับนอกประเทศไทย",
        timeSettingsTitle: "ตั้งเวลาเริ่มต้น",
        timeSettingsMinutes: "นาที",
        timeSettingsSeconds: "วินาที",
        logoPathTitle: "ที่อยู่โฟลเดอร์โลโก้ & Cache",
        logoPathDesc: "ที่อยู่โฟลเดอร์โลโก้ OBS ปัจจุบันคือ:",
        logoPathHint: "ตั้งค่าที่อยู่โฟลเดอร์โลโก้",
        changelogTitle: "ประวัติการอัปเดต",
        changelogContent: `
            <ul class="changelog-list">
                <li>
                    <h5>เวอร์ชัน 2.9.2</h5>
                    <ul>
                        <li>**ตั้งค่า:** จัดเรียงเป็นแท็บ (ประกาศ, ปุ่ม, คีย์ลัด, แสดงผล, ข้อมูล) เข้าถึงง่ายขึ้น</li>
                        <li>**UI:** ปุ่มสีใหญ่ขึ้น, เลือกแสดง 1 หรือ 2 สี, สถานะ timer (เดิน/หยุด)</li>
                        <li>**UX:** ยืนยันก่อน full reset, Enter/Escape แก้ชื่อทีม, tooltips</li>
                        <li>**OBS:** สร้าง sources อัตโนมัติใน scene ปัจจุบันผ่าน WebSocket</li>
                        <li>**แก้บั๊ก:** Popup มัวใน OBS Dock, CSS syntax error, viewport meta, toast</li>
                        <li>**สนับสนุน:** หน้า donate/sponsor ออกแบบใหม่</li>
                    </ul>
                </li>
                <li>
                    <h5>เวอร์ชัน 2.9</h5>
                    <ul>
                        <li>จำนวนคนออนไลน์, Responsive, ซ่อน/แสดงปุ่มเสริม, Logo Cache, Google Sheets</li>
                    </ul>
                </li>
            </ul> `,
        toastLoadFileFirst: "โปรด Upload ไฟล์ก่อน",
        toastMatchNotFound: "ไม่พบ Match ID:",
        toastLoaded: "โหลด ID สำเร็จ:",
        toastSuccess: "สำเร็จ",
        toastSwapped: "สลับฝั่งทีมแล้ว",
        toastNoTextToCopy: "ไม่มีข้อความให้คัดลอก",
        toastCopied: "คัดลอกแล้ว",
        toastCopyFailed: "คัดลอกล้มเหลว",
        toastScoreReset: "รีเซ็ตคะแนนแล้ว",
        toastScore2Reset: "รีเซ็ตคะแนน 2 แล้ว",
        toastFullReset: "รีเซ็ตสกอร์บอร์ดทั้งหมดแล้ว",
        toastCopiedSourceName: "คัดลอกชื่อ Source แล้ว:",
        toastSaved: "บันทึกแล้ว",
        toastKeybindsSaved: "บันทึกคีย์ลัดแล้ว!",
        toastActionSaved: "บันทึกการตั้งค่า Action Button แล้ว! (ควบคุม Source)",
        toastColorsCleared: "ล้างหน่วยความจำสีทีมแล้ว!",
        toastObsError: "เชื่อมต่อ OBS ไม่สำเร็จ",
        toastActionControlFailed: "ส่งคำสั่งควบคุม Source ไม่สำเร็จ:",
        toastInvalidTime: "รูปแบบเวลาไม่ถูกต้อง กรุณาตรวจสอบนาทีและวินาที (0-59)",
        toastTimeSet: "ตั้งค่าและอัปเดตเวลาเริ่มต้นแล้ว",
        logoCacheTitle: "Logo Cache (การแสดงผล Dock UI)",
        logoCacheDesc: "ลากไฟล์โลโก้ (PNG/JPG) มาวางที่นี่เพื่อแสดงบน Dock UI โดยตรงเพื่อเลี่ยงข้อจำกัดด้านความปลอดภัยของไฟล์ในเบราว์เซอร์ ชื่อไฟล์ (ไม่ต้องใส่นามสกุล) จะเป็นชื่อ Key ของโลโก้",
        logoDropZoneText: "ลากและวางไฟล์โลโก้ที่นี่",
        logoCacheListTitle: "โลโก้ที่ถูก Cache ไว้:",
        logoCacheEmpty: "ไม่มีโลโก้ถูก Cache ไว้",
        logoCacheSaved: "บันทึกโลโก้ลง Cache แล้ว:",
        toastCacheSaveFailed: "บันทึกโลโก้ลง Cache ล้มเหลว!",
        clearCache: "ล้าง Logo Cache",
        toastCacheCleared: "ล้าง Logo Cache แล้ว!",
        logoCacheSummary: "สรุปการนำเข้า:",
        logoCacheSuccess: "สำเร็จ:",
        logoCacheFailed: "ล้มเหลว:",
        logoCacheTotal: "จำนวนโลโก้ใน Cache:",

        // NEW STRINGS FOR V2.8
        mobileControlTitle: "ควบคุมผ่านมือถือ (OBSScore Remote)",
        mobileControlDesc: "ควบคุมสกอร์บอร์ดผ่านอินเทอร์เน็ตด้วยมือถือ",
        createRoom: "สร้างห้อง",
        roomName: "ชื่อห้อง",
        roomId: "รหัสห้อง",
        scanQr: "สแกน QR Code เพื่อเชื่อมต่อ",
        waitingConnection: "กำลังรอการเชื่อมต่อ...",
        connectedDevice: "อุปกรณ์ที่เชื่อมต่อ:",
        disconnect: "ตัดการเชื่อมต่อ",
        openMobileApp: "เปิดหน้าเว็บมือถือ",
        remoteStatus: "สถานะ:",
        remoteStatusWait: "เตรียมพร้อม",
        remoteStatusReady: "รอการจับคู่",
        remoteStatusConnected: "เชื่อมต่อแล้ว",
        dataSourceTitle: "ตั้งค่าแหล่งข้อมูล (Data Source)",
        dsExcel: "ไฟล์ Excel (ออฟไลน์)",
        dsGoogleSheet: "Google Sheet (ออนไลน์)",
        confirm: "ยืนยันตกลง",
        toastGoogleSheetSuccess: "ดึงข้อมูลจาก Google Sheet สำเร็จ!",
        toastGoogleSheetError: "ดึงข้อมูลไม่สำเร็จ ตรวจสอบ URL หรือการแชร์",
        loadFromGoogleSheet: "ดึงข้อมูล GS",
        labelCount: "จำนวนป้าย:",
    },
};